// Forgotten Armament - Create New Items NWN

/*************************************************************************/
///////////////////////////////////////////////////////////////////////////
// CREATE NEW MELEE WEAPONS                                              //
///////////////////////////////////////////////////////////////////////////
/*************************************************************************/

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Axes                                                                  //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Create Deepstone Progeny +2 - Assign to                                                       //
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN
    COPY ~forgotten-armament/itm/MOAX01.ITM~ ~override/MOAX01.ITM~
        SAY NAME1 @10000
        SAY NAME2 @10006
        SAY UNIDENTIFIED_DESC @10001
        SAY DESC @10007


END

///////////////////////////////////////////////////////////////////////////
// Create Axe of Dead Illusk +2 - Assign to Maferan                      //
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN
    COPY ~forgotten-armament/itm/MOAX02.ITM~ ~override/MOAX02.ITM~
        SAY NAME1 @10000
        SAY NAME2 @10008
        SAY UNIDENTIFIED_DESC @10001
        SAY DESC @10009

    COPY_EXISTING ~HLMAFER.CRE~ ~override~
        SET_BG2_PROFICIENCY ~PROFICIENCYAXE~ 5
        REPLACE_CRE_ITEM ~MOAX02~ #0 #0 #0 ~UNSTEALABLE~ ~WEAPON1~ EQUIP
END

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Bastard Swords                                                        //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Create Nameless Light +2 - Assign to Jardak in Northern Baldur's Gate //
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bgee eet~) BEGIN
    COPY ~forgotten-armament/itm/MO1H42.ITM~ ~override/MO1H42.ITM~
        SAY NAME1 @10100
        SAY NAME2 @10102
        SAY UNIDENTIFIED_DESC @10101
        SAY DESC @10103

    COPY_EXISTING ~JARDAK.CRE~ ~override~
        SET_BG2_PROFICIENCY ~PROFICIENCYBASTARDSWORD~ 5
        REPLACE_CRE_ITEM ~MO1H42~ #0 #0 #0 ~UNSTEALABLE~ ~WEAPON1~ EQUIP
END

///////////////////////////////////////////////////////////////////////////
// Create Bloodletter +4 - Assign to Revanek in the Twisted Rune         //
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN
    ACTION_IF NOT FILE_EXISTS_IN_GAME ~BDSW1H21.SPL~ BEGIN
        COPY ~forgotten-armament/spl/BDSW1H21.SPL~ ~override/BDSW1H21.SPL~
    END
    
    COPY ~forgotten-armament/itm/MO1H39.ITM~ ~override/MO1H39.ITM~
        SAY NAME1 @10100
        SAY NAME2 @10106
        SAY UNIDENTIFIED_DESC @10101
        SAY DESC @10107

    COPY_EXISTING ~HLREVAN.CRE~ ~override~
        SET_BG2_PROFICIENCY ~PROFICIENCYBASTARDSWORD~ 5
        REPLACE_CRE_ITEM ~MO1H39~ #0 #0 #0 ~UNSTEALABLE~ ~WEAPON1~ EQUIP
END

///////////////////////////////////////////////////////////////////////////
// Create Discord +2 - Assign to Simyaz in Underdark                     //
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN
    COPY ~forgotten-armament/spl/MO1H30.SPL~ ~override/MO1H30.SPL~
    COPY ~forgotten-armament/itm/MO1H03.ITM~ ~override/MO1H03.ITM~
        SAY NAME1 @10100
        SAY NAME2 @10108
        SAY UNIDENTIFIED_DESC @10101
        SAY DESC @10109

    COPY_EXISTING ~UDSIMYAZ.CRE~ ~override~
        SET_BG2_PROFICIENCY ~PROFICIENCYBASTARDSWORD~ 2
        REPLACE_CRE_ITEM ~MO1H03~ #0 #0 #0 ~UNSTEALABLE~ ~WEAPON1~ EQUIP
END

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Daggers                                                               //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Create Myr Styah'be'eh +4 - Assign to                                                       //
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN
    COPY ~forgotten-armament/itm/MODAG01.ITM~ ~override/MODAG01.ITM~
        SAY NAME1 @10300
        SAY NAME2 @10308
        SAY UNIDENTIFIED_DESC @10301
        SAY DESC @10309


END

///////////////////////////////////////////////////////////////////////////
// Create Ice Talon +2 - Assign to            //
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN
    ACTION_IF NOT FILE_EXISTS_IN_GAME ~IBDDAG01.BAM~ BEGIN
        COPY ~forgotten-armament/bam/IBDDAG01.BAM~ ~override/IBDDAG01.BAM~
    END

    COPY ~forgotten-armament/itm/MODAG02.ITM~ ~override/MODAG02.ITM~
        SAY NAME1 @10300
        SAY NAME2 @10310
        SAY UNIDENTIFIED_DESC @10301
        SAY DESC @10311


END

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Halberds                                                              //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Create Cruel Halberd +3 - Assign to                                                      //
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN
    COPY ~forgotten-armament/spl/MOHAL01.SPL~ ~override/MOHAL01.SPL~
    COPY ~forgotten-armament/itm/MOHAL01.ITM~ ~override/MOHAL01.ITM~
        SAY NAME1 @10500
        SAY NAME2 @10502
        SAY UNIDENTIFIED_DESC @10501
        SAY DESC @10503


END

///////////////////////////////////////////////////////////////////////////
// Create Will of Atar +1 - Assign to                                                      //
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN
    COPY ~forgotten-armament/itm/MOHAL02.ITM~ ~override/MOHAL02.ITM~
        SAY NAME1 @10500
        SAY NAME2 @10504
        SAY UNIDENTIFIED_DESC @10501
        SAY DESC @10505


END

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Katanas                                                               //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Master Li's Way +2 - Assign to Kahrk in Firewine Bridge               //
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bgee eet~) BEGIN
    COPY ~forgotten-armament/itm/MO1H55.ITM~ ~override/MO1H55.ITM~
        SAY NAME1 @10600
        SAY NAME2 @10602
        SAY UNIDENTIFIED_DESC @10601
        SAY DESC @10603

    COPY_EXISTING ~KAHRK.CRE~ ~override~
        REPLACE_CRE_ITEM ~MO1H55~ #0 #0 #0 ~UNSTEALABLE~ ~WEAPON1~ EQUIP
END

///////////////////////////////////////////////////////////////////////////
// Naught Katana +5 - Assign to Xei Win Toh in Watcher's Keep Seal       //
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN
    COPY ~forgotten-armament/itm/MO1H75.ITM~ ~override/MO1H75.ITM~
        SAY NAME1 @10600
        SAY NAME2 @10604
        SAY UNIDENTIFIED_DESC @10601
        SAY DESC @10605
    COPY ~forgotten-armament/eff/MO1H75.EFF~ ~override/MO1H75.EFF~

    COPY_EXISTING ~GORWOM06.CRE~ ~override~
        SET_BG2_PROFICIENCY ~PROFICIENCYKATANA~ 5
        REPLACE_CRE_ITEM ~MO1H75~ #0 #0 #0 ~UNSTEALABLE~ ~WEAPON1~ EQUIP
END

///////////////////////////////////////////////////////////////////////////
// Kaga-To +1 - Assign to Haseo in the Undercity                         //
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bgee eet~) BEGIN
    COPY ~forgotten-armament/itm/MO1H40.ITM~ ~override/MO1H40.ITM~
        SAY NAME1 @10600
        SAY NAME2 @10606
        SAY UNIDENTIFIED_DESC @10601
        SAY DESC @10607

    COPY_EXISTING ~HASEO.CRE~ ~override~
        REPLACE_CRE_ITEM ~MO1H40~ #0 #0 #0 ~UNSTEALABLE~ ~WEAPON1~ EQUIP
END

///////////////////////////////////////////////////////////////////////////
// Dragonsblood Katana +2 - Assign to Akae in Firkraag Dungeon           //
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN
    COPY ~forgotten-armament/itm/MO1H01.ITM~ ~override/MO1H01.ITM~
        SAY NAME1 @10600
        SAY NAME2 @10608
        SAY UNIDENTIFIED_DESC @10601
        SAY DESC @10609

    COPY_EXISTING ~AKAE.CRE~ ~override~
        REPLACE_CRE_ITEM ~MO1H01~ #0 #0 #0 ~UNSTEALABLE~ ~WEAPON1~ EQUIP
END

///////////////////////////////////////////////////////////////////////////
// The Devoted Servant +1 - Assign to Ogre Mage Cloakwood Mine           //
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bgee eet~) BEGIN
    COPY ~forgotten-armament/itm/MO1H02.ITM~ ~override/MO1H02.ITM~
        SAY NAME1 @10600
        SAY NAME2 @10610
        SAY UNIDENTIFIED_DESC @10601
        SAY DESC @10611

    COPY_EXISTING ~OGREMA03.CRE~ ~override~
        REPLACE_CRE_ITEM ~MO1H02~ #0 #0 #0 ~UNSTEALABLE~ ~WEAPON1~ EQUIP
END

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Long Swords                                                           //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Create Blade of the Gladiator + 2 - Assign to        //
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN
    COPY ~forgotten-armament/itm/MO1H06.ITM~ ~override/MO1H06.ITM~
        SAY NAME1 @10710
        SAY NAME2 @10712
        SAY UNIDENTIFIED_DESC @10711
        SAY DESC @10713


END

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Maces                                                           //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Create Petty's Tempest +2 - Assign to                                          //
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN
    COPY ~forgotten-armament/itm/MOBLN01.ITM~ ~override/MOBLN01.ITM~
        SAY NAME1 @10800
        SAY NAME2 @10803
        SAY UNIDENTIFIED_DESC @10801
        SAY DESC @10804


END

///////////////////////////////////////////////////////////////////////////
// Create Soldier's Might +2 - Assign to Stalman                         //
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN
    COPY ~forgotten-armament/itm/MOBLN02.ITM~ ~override/MOBLN02.ITM~
        SAY NAME1 @10800
        SAY NAME2 @10805
        SAY UNIDENTIFIED_DESC @10801
        SAY DESC @10806

    COPY_EXISTING ~HLSTAL.CRE~ ~override~
        REPLACE_CRE_ITEM ~MOBLN02~ #0 #0 #0 ~UNSTEALABLE~ ~WEAPON1~
END

///////////////////////////////////////////////////////////////////////////
// Create Chef Gronk's Tenderizer +2 - Assign to Entu in Planar Sphere   //
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN
    COPY ~forgotten-armament/itm/MOBLN03.ITM~ ~override/MOBLN03.ITM~
        SAY NAME1 @10800
        SAY NAME2 @10807
        SAY UNIDENTIFIED_DESC @10801
        SAY DESC @10808

    COPY_EXISTING ~OBSHAL01.CRE~ ~override~
        SET_BG2_PROFICIENCY ~PROFICIENCYMACE~ 5
        SET_BG2_PROFICIENCY ~PROFICIENCYSINGLEWEAPON~ 2
        REPLACE_CRE_ITEM ~MOBLN03~ #0 #0 #0 ~UNSTEALABLE~ ~WEAPON1~
END

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Morning Stars                                                         //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Create Sleepwalker Kin +2 - Assign to                                      //
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN
    COPY ~forgotten-armament/itm/MOMS01.ITM~ ~override/MOMS01.ITM~
        SAY NAME1 @10900
        SAY NAME2 @10902
        SAY UNIDENTIFIED_DESC @10901
        SAY DESC @10903


END

///////////////////////////////////////////////////////////////////////////
// Create Bone Phoenix +1 - Assign to                                      //
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN
    COPY ~forgotten-armament/itm/MOMS02.ITM~ ~override/MOMS02.ITM~
        SAY NAME1 @10900
        SAY NAME2 @10904
        SAY UNIDENTIFIED_DESC @10901
        SAY DESC @10905


END

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Ninja-Tos                                                             //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Create Courtesan Blade + 2 - Assign to Akae in Firkraag Dungeon       //
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN
    COPY ~forgotten-armament/itm/MO1H04.ITM~ ~override/MO1H04.ITM~
        SAY NAME1 @11000
        SAY NAME2 @11002
        SAY UNIDENTIFIED_DESC @11001
        SAY DESC @11003

    COPY_EXISTING ~AKAE.CRE~ ~override~
        REPLACE_CRE_ITEM ~MO1H04~ #0 #0 #0 ~UNSTEALABLE~ ~SHIELD~
END

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Quarterstaves                                                         //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Create Rakshasa Staff +3 - Assign to Ihtafeer                         //
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN
    COPY ~forgotten-armament/itm/MOSTA01.ITM~ ~override/MOSTA01.ITM~
        SAY NAME1 @11100
        SAY NAME2 @11102
        SAY UNIDENTIFIED_DESC @11101
        SAY DESC @11103

    COPY_EXISTING ~TRRAK01.CRE~ ~override~
        REPLACE_CRE_ITEM ~MOSTA01~ #0 #0 #0 ~UNSTEALABLE~ ~WEAPON1~ EQUIP
END

///////////////////////////////////////////////////////////////////////////
// Create Remembrance +3 - Assign in BGEE and BG2EE                      //
///////////////////////////////////////////////////////////////////////////
COPY ~forgotten-armament/itm/MOSTA02.ITM~ ~override/MOSTA02.ITM~
    SAY NAME1 @11100
    SAY NAME2 @11104
    SAY UNIDENTIFIED_DESC @11101
    SAY DESC @11105

ACTION_IF (GAME_IS ~bgee eet~) BEGIN
    COPY_EXISTING ~TRACEA.CRE~ ~override~ // Assign to Tracea Carol in fight against Aec'letec
        REPLACE_CRE_ITEM ~MOSTA02~ #0 #0 #0 ~UNSTEALABLE~ ~WEAPON1~ EQUIP
END

ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN
    COPY_EXISTING ~GPMAGE1.CRE~ ~override~ // Assign to N'ashtar in Underdark
        REPLACE_CRE_ITEM ~MOSTA02~ #0 #0 #0 ~UNSTEALABLE~ ~WEAPON1~ EQUIP
END

///////////////////////////////////////////////////////////////////////////
// Create Staff of Balpheron +1 - Assign to Conster                      //
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN
    COPY ~forgotten-armament/itm/MOSTA03.ITM~ ~override/MOSTA03.ITM~
        SAY NAME1 @11100
        SAY NAME2 @11106
        SAY UNIDENTIFIED_DESC @11101
        SAY DESC @11107

    COPY_EXISTING ~FIRMAG01.CRE~ ~override~
        REPLACE_CRE_ITEM ~MOSTA03~ #0 #0 #0 ~UNSTEALABLE~ ~WEAPON1~ EQUIP
END

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Scimitars                                                             //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Create Spider's Kiss +2 - Assign to Pai'Na Below Graveyard            //
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN
    COPY ~forgotten-armament/itm/MO1H50.ITM~ ~override/MO1H50.ITM~
        SAY NAME1 @11200
        SAY NAME2 @11202
        SAY UNIDENTIFIED_DESC @11201
        SAY DESC @11203

    COPY_EXISTING ~SPPAIN.CRE~ ~override~
        SET_BG2_PROFICIENCY ~PROFICIENCYSCIMITARWAKISASHININJATO~ 1
        SET_BG2_PROFICIENCY ~PROFICIENCYSINGLEWEAPON~ 1
        REPLACE_CRE_ITEM ~MO1H50~ #0 #0 #0 ~UNSTEALABLE~ ~WEAPON1~ EQUIP

    // Assign Sod2BG2 item to Deidre in Adventurer's Mart
    ACTION_IF FILE_EXISTS_IN_GAME ~dtkrnd02.itm~ BEGIN
        COPY_EXISTING ~WMART2.STO~ ~override~
            ADD_STORE_ITEM ~dtkrnd02~ #0 #0 #0 ~IDENTIFIED~ #1
    END
END

///////////////////////////////////////////////////////////////////////////
// Create Laughing Blade +2 - Assign to Samia in Firkraag's Dungeon      //
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN
    COPY ~forgotten-armament/itm/MO1H30.ITM~ ~override/MO1H30.ITM~
        SAY NAME1 @11200
        SAY NAME2 @11206
        SAY UNIDENTIFIED_DESC @11201
        SAY DESC @11207

    COPY_EXISTING ~SAMIA.CRE~ ~override~
        REPLACE_CRE_ITEM ~MO1H30~ #0 #0 #0 ~UNSTEALABLE~ ~WEAPON1~ EQUIP
END

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Spears                                                                //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Create Briarspike +2 - Assign to Seniyad in Cloakwood                 //
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bgee eet~) BEGIN
    COPY ~forgotten-armament/itm/MOSP01.ITM~ ~override/MOSP01.ITM~
        SAY NAME1 @11400
        SAY NAME2 @11402
        SAY UNIDENTIFIED_DESC @11401
        SAY DESC @11403

    COPY_EXISTING ~SENIYA.CRE~ ~override~
        SET_BG2_PROFICIENCY ~PROFICIENCYSPEAR~ 1
        REPLACE_CRE_ITEM ~MOSP01~ #0 #0 #0 ~UNSTEALABLE~ ~WEAPON1~ EQUIP
END

///////////////////////////////////////////////////////////////////////////
// Create Heartwood Spear +4 - Assign to                                         //
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN
    COPY ~forgotten-armament/itm/MOSP02.ITM~ ~override/MOSP02.ITM~
        SAY NAME1 @11400
        SAY NAME2 @11406
        SAY UNIDENTIFIED_DESC @11401
        SAY DESC @11407


END

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Two-Handed Swords                                                     //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Create Blade of the Rashemi +3 - Assign to Olaf Rassmusen             //
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN
    COPY ~forgotten-armament/itm/MO2H01.ITM~ ~override/MO2H01.ITM~
        SAY NAME1 @11500
        SAY NAME2 @11508
        SAY UNIDENTIFIED_DESC @11501
        SAY DESC @11509

    COPY_EXISTING ~HLOLAF.CRE~ ~override~
        REPLACE_CRE_ITEM ~MOFP03~ #0 #0 #0 ~UNSTEALABLE~ ~WEAPON1~ EQUIP
END

///////////////////////////////////////////////////////////////////////////
// Create The Golem's Blade +3 - Assign to                                          //
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN
    COPY ~forgotten-armament/spl/MO2H02.SPL~ ~override/MO2H02.SPL~
    COPY ~forgotten-armament/itm/MO2H02.ITM~ ~override/MO2H02.ITM~
        SAY NAME1 @11500
        SAY NAME2 @11510
        SAY UNIDENTIFIED_DESC @11501
        SAY DESC @11511


END

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Wakizashis                                                            //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Create Eye of the Sun +3 - Assign to Koshi                            //
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bgee eet~) BEGIN
    COPY ~forgotten-armament/itm/MO1H05.ITM~ ~override/MO1H05.ITM~
        SAY NAME1 @11600
        SAY NAME2 @11602
        SAY UNIDENTIFIED_DESC @11601
        SAY DESC @11603

    COPY_EXISTING ~HLKOSHI.CRE~ ~override~
        SET_BG2_PROFICIENCY ~PROFICIENCYSCIMITARWAKISASHININJATO~ 2
        SET_BG2_PROFICIENCY ~PROFICIENCY2WEAPON~ 2
        REPLACE_CRE_ITEM ~MO1H05~ #0 #0 #0 ~UNSTEALABLE~ ~SHIELD~ EQUIP
END

///////////////////////////////////////////////////////////////////////////
// Create The Dark Companion +4 - Assign to Xei Win Toh                  //
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bgee eet~) BEGIN
    COPY ~forgotten-armament/spl/MO1H07.SPL~ ~override/MO1H07.SPL~
    COPY ~forgotten-armament/itm/MO1H07.ITM~ ~override/MO1H07.ITM~
        SAY NAME1 @11600
        SAY NAME2 @11604
        SAY UNIDENTIFIED_DESC @11601
        SAY DESC @11605

    COPY_EXISTING ~GORWOM06.CRE~ ~override~
        SET_BG2_PROFICIENCY ~PROFICIENCYSCIMITARWAKISASHININJATO~ 5
        REPLACE_CRE_ITEM ~MO1H07~ #0 #0 #0 ~UNSTEALABLE~ ~SHIELD~ EQUIP
END

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// War Hammers                                                           //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Create Lesser Rift Hammer +1 - Assign to Diyab in Iron Throne Tower   //
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bgee eet~) BEGIN
    COPY ~forgotten-armament/itm/MOHM01.ITM~ ~override/MOHM01.ITM~
        SAY NAME1 @11700
        SAY NAME2 @11702
        SAY UNIDENTIFIED_DESC @11701
        SAY DESC @11703

    COPY_EXISTING ~DIYAB.CRE~ ~override~
        REPLACE_CRE_ITEM ~MOHM01~ #0 #0 #0 ~UNSTEALABLE~ ~WEAPON1~ EQUIP
END

///////////////////////////////////////////////////////////////////////////
// Create Rift Hammer +3 -                                                           //
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN
    COPY ~forgotten-armament/itm/MOHM02.ITM~ ~override/MOHM02.ITM~
        SAY NAME1 @11700
        SAY NAME2 @11705
        SAY UNIDENTIFIED_DESC @11701
        SAY DESC @11706


END

/*************************************************************************/
///////////////////////////////////////////////////////////////////////////
// CREATE ARMORS                                                         //
///////////////////////////////////////////////////////////////////////////
/*************************************************************************/

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Robes                                                                 //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Create Tasha's Atrocious Robe - Assign to N'ashtar in the Underdark   //
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN
    COPY ~forgotten-armament/itm/MORB01.ITM~ ~override/MORB01.ITM~
        SAY NAME1 @12200
        SAY NAME2 @12206
        SAY UNIDENTIFIED_DESC @12201
        SAY DESC @12207

    COPY_EXISTING ~GPMAGE1.CRE~ ~override~ 
        REPLACE_CRE_ITEM ~MOSTA02~ #0 #0 #0 ~UNSTEALABLE~ ~ARMOR~ EQUIP
END

///////////////////////////////////////////////////////////////////////////
// Create Will of the Wychlaran - Assign to Sion                         //
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN
    COPY ~forgotten-armament/itm/MORB02.ITM~ ~override/MORB02.ITM~
        SAY NAME1 @12200
        SAY NAME2 @12208
        SAY UNIDENTIFIED_DESC @12201
        SAY DESC @12209

    COPY_EXISTING ~HLSION.CRE~ ~override~
        REPLACE_CRE_ITEM ~MORB02~ #0 #0 #0 ~UNSTEALABLE~ ~ARMOR~ EQUIP
END

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Leather Armors                                                        //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Create Armor of Loyalty - Assign to                                           //
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN
    COPY ~forgotten-armament/itm/MOLEA01.ITM~ ~override/MOLEA01.ITM~
        SAY NAME1 @12300
        SAY NAME2 @12302
        SAY UNIDENTIFIED_DESC @12301
        SAY DESC @12303


END

///////////////////////////////////////////////////////////////////////////
// Create Aurumvorax Armor - Assign to Dalok in Druid Grove              //
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN
    COPY ~forgotten-armament/itm/MOLEA02.ITM~ ~override/MOLEA02.ITM~
        SAY NAME1 @12300
        SAY NAME2 @12304
        SAY UNIDENTIFIED_DESC @12301
        SAY DESC @12305

    COPY_EXISTING ~CEDRUID2.CRE~ ~override~
        REPLACE_CRE_ITEM ~MOLEA02~ #0 #0 #0 ~UNSTEALABLE~ ~ARMOR~ EQUIP
END

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Studded Leather Armors                                                //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Create Black Flame Armor - Assign to                                                 //
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN
    COPY ~forgotten-armament/itm/MOLEA03.ITM~ ~override/MOLEA03.ITM~
        SAY NAME1 @12400
        SAY NAME2 @12402
        SAY UNIDENTIFIED_DESC @12401
        SAY DESC @12403


END

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Chain Mail Armors                                                     //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Create Anti-Venom Chainmail - Assign to                                                 //
///////////////////////////////////////////////////////////////////////////
COPY ~forgotten-armament/itm/MOCM01.ITM~ ~override/MOCM01.ITM~
    SAY NAME1 @12600
    SAY NAME2 @12604
    SAY UNIDENTIFIED_DESC @12601
    SAY DESC @12605

ACTION_IF (GAME_IS ~bgee eet~) BEGIN
    // BGEE Install
END

ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN
    // BG2EE Install
END

///////////////////////////////////////////////////////////////////////////
// Create Doron's Mistake - Assign to                                                 //
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN
    COPY ~forgotten-armament/itm/MOCM02.ITM~ ~override/MOCM02.ITM~
        SAY NAME1 @12600
        SAY NAME2 @12606
        SAY UNIDENTIFIED_DESC @12601
        SAY DESC @12607


END

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Plate Mail Armors                                                     //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Create The Gilded Defender - Assign to Duerger Store Underdark        // 
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN
    COPY ~forgotten-armament/itm/MOPM01.ITM~ ~override/MOPM01.ITM~
        SAY NAME1 @12800
        SAY NAME2 @12802
        SAY UNIDENTIFIED_DESC @12801
        SAY DESC @12803

    COPY_EXISTING ~UDDUER01.STO~ ~override~
        ADD_STORE_ITEM ~MOPM01~ #0 #0 #0 ~IDENTIFIED~ #1
END

///////////////////////////////////////////////////////////////////////////
// Create Deep Guardian's Plate - Assign to Revanek in the Twisted Rune  // 
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN
    COPY ~forgotten-armament/itm/MOPM02.ITM~ ~override/MOPM02.ITM~
        SAY NAME1 @12800
        SAY NAME2 @12804
        SAY UNIDENTIFIED_DESC @12801
        SAY DESC @12805

    COPY_EXISTING ~HLREVAN.CRE~ ~override~
        REPLACE_CRE_ITEM ~MOPMO2~ #0 #0 #0 ~UNSTEALABLE~ ~ARMOR~ EQUIP
END

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Full Plate Armors                                                     //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Storm Armor of the Earth's Children - Assign to Legdor in Firkraag    //
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN
    COPY ~forgotten-armament/itm/MOFP01.ITM~ ~override/MOFP01.ITM~
        SAY NAME1 @12900
        SAY NAME2 @12902
        SAY UNIDENTIFIED_DESC @12901
        SAY DESC @12903

    COPY_EXISTING ~LEGDOR.CRE~ ~override~
        REPLACE_CRE_ITEM ~MOFP01~ #0 #0 #0 ~UNSTEALABLE~ ~ARMOR~ EQUIP
END

///////////////////////////////////////////////////////////////////////////
// Create Armor of Gram the Mouse - Assign to                                 //
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN
    COPY ~forgotten-armament/itm/MOFP02.ITM~ ~override/MOFP02.ITM~
        SAY NAME1 @12900
        SAY NAME2 @12904
        SAY UNIDENTIFIED_DESC @12901
        SAY DESC @12905


END

///////////////////////////////////////////////////////////////////////////
// Create Armor of Freedom - Assign to Olaf Rassmusen                    //
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN
    COPY ~forgotten-armament/itm/MOFP03.ITM~ ~override/MOFP03.ITM~
        SAY NAME1 @12900
        SAY NAME2 @12906
        SAY UNIDENTIFIED_DESC @12901
        SAY DESC @12907

    COPY_EXISTING ~HLOLAF.CRE~ ~override~
        REPLACE_CRE_ITEM ~MOFP03~ #0 #0 #0 ~UNSTEALABLE~ ~ARMOR~ EQUIP
END

/*************************************************************************/
///////////////////////////////////////////////////////////////////////////
// CREATE SHIELDS                                                        //
///////////////////////////////////////////////////////////////////////////
/*************************************************************************/

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Bucklers                                                              //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Create Shield of the Magi - Assign to Sion                            //
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN
    COPY ~forgotten-armament/itm/MOBSH01.ITM~ ~override/MOBSH01.ITM~
        SAY NAME1 @13000
        SAY NAME2 @13002
        SAY UNIDENTIFIED_DESC @13001
        SAY DESC @13003

    COPY_EXISTING ~HLSION.CRE~ ~override~
        REPLACE_CRE_ITEM ~MOBSH01~ #0 #0 #0 ~UNSTEALABLE~ ~SHIELD~ EQUIP
END

///////////////////////////////////////////////////////////////////////////
// Create Dwarven Mirth - Assign to                                                //
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN
    COPY ~forgotten-armament/itm/MOBSH02.ITM~ ~override/MOBSH02.ITM~
        SAY NAME1 @13000
        SAY NAME2 @13004
        SAY UNIDENTIFIED_DESC @13001
        SAY DESC @13005


END

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Small Shields                                                         //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Create The Frostmaiden's Bane - Assign to Stalman                     //
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN
    COPY ~forgotten-armament/itm/MOSSH01.ITM~ ~override/MOSSH01.ITM~
        SAY NAME1 @13100
        SAY NAME2 @13104
        SAY UNIDENTIFIED_DESC @13101
        SAY DESC @13105

    COPY_EXISTING ~HLSTAL.CRE~ ~override~
        SET_BG2_PROFICIENCY ~PROFICIENCYSWORDANDSHIELD~ 1
        REPLACE_CRE_ITEM ~MOSSH01~ #0 #0 #0 ~UNSTEALABLE~ ~SHIELD~
END

///////////////////////////////////////////////////////////////////////////
// Create Protector - Assign to                                            //
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN
    COPY ~forgotten-armament/itm/MOSSH02.ITM~ ~override/MOSSH02.ITM~
        SAY NAME1 @13100
        SAY NAME2 @13106
        SAY UNIDENTIFIED_DESC @13101
        SAY DESC @13107


END

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Medium Shields                                                        //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Create Laeral's Spell Shield +1 - Assigned to                                        //
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN
    COPY ~forgotten-armament/itm/MOMSH01.ITM~ ~override/MOMSH01.ITM~
        SAY NAME1 @13200
        SAY NAME2 @13204
        SAY UNIDENTIFIED_DESC @13201
        SAY DESC @13205
        
END

///////////////////////////////////////////////////////////////////////////
// Create Silver Shield +2 - Assigned to Simyaz in Underdark             //
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN
    COPY ~forgotten-armament/itm/MOMSH02.ITM~ ~override/MOMSH02.ITM~
        SAY NAME1 @13200
        SAY NAME2 @13206
        SAY UNIDENTIFIED_DESC @13201
        SAY DESC @13207

    COPY_EXISTING ~UDSIMYAZ.CRE~ ~override~
        REPLACE_CRE_ITEM ~MOMSH02~ #0 #0 #0 ~UNSTEALABLE~ ~SHIELD~        
END

///////////////////////////////////////////////////////////////////////////
// Create Uthgardt Holy Shield +2 - Assigned to Revanek                  //
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN
    COPY ~forgotten-armament/itm/MOMSH03.ITM~ ~override/MOMSH03.ITM~
        SAY NAME1 @13200
        SAY NAME2 @13208
        SAY UNIDENTIFIED_DESC @13201
        SAY DESC @13209

    COPY_EXISTING ~HLREVAN.CRE~ ~override~
        REPLACE_CRE_ITEM ~MOMSH03~ #0 #0 #0 ~UNSTEALABLE~ ~SHIELD~       
END

///////////////////////////////////////////////////////////////////////////
// Create Kepeturi Crest +3 - Assigned to              //
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN
    COPY ~forgotten-armament/itm/MOMSH04.ITM~ ~override/MOMSH04.ITM~
        SAY NAME1 @13200
        SAY NAME2 @13210
        SAY UNIDENTIFIED_DESC @13201
        SAY DESC @13211

      
END

///////////////////////////////////////////////////////////////////////////
// Create Triune Shield +3 - Assigned to              //
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN
    COPY ~forgotten-armament/itm/MOMSH05.ITM~ ~override/MOMSH05.ITM~
        SAY NAME1 @13200
        SAY NAME2 @13212
        SAY UNIDENTIFIED_DESC @13201
        SAY DESC @13213

      
END

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Create Large Shields                                                  //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////



/*************************************************************************/
///////////////////////////////////////////////////////////////////////////
// CREATE ACCESSORIES                                                    //
///////////////////////////////////////////////////////////////////////////
/*************************************************************************/

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Amulets                                                               //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Periapt of Wisdom +2 - Setup for BG2EE                                            //
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN
    COPY ~forgotten-armament/itm/MOAM01.ITM~ ~override/MOAM01.ITM~
        SAY NAME1 @13400
        SAY NAME2 @13402
        SAY UNIDENTIFIED_DESC @13401
        SAY DESC @13403

    COPY_EXISTING ~HLSTAL.CRE~ ~override~
        REPLACE_CRE_ITEM ~MOAM01~ #0 #0 #0 ~UNSTEALABLE~ ~AMULET~ EQUIP
END

///////////////////////////////////////////////////////////////////////////
// Amulet of Health - Setup for BG2EE                                                  //
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN
    COPY ~forgotten-armament/itm/MOAM02.ITM~ ~override/MOAM02.ITM~
        SAY NAME1 @13400
        SAY NAME2 @13404
        SAY UNIDENTIFIED_DESC @13401
        SAY DESC @13405
END

///////////////////////////////////////////////////////////////////////////
// Amulet of Pure Love - Setup for ToB                                                  //
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN
    COPY ~forgotten-armament/itm/MOAM03.ITM~ ~override/MOAM03.ITM~
        SAY NAME1 @13400
        SAY NAME2 @13406
        SAY UNIDENTIFIED_DESC @13401
        SAY DESC @13407
END

///////////////////////////////////////////////////////////////////////////
// Ysridain's Soul - Assign to Aawill (Planar Hunter)                    //
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN
    COPY ~forgotten-armament/itm/MOAM04.ITM~ ~override/MOAM04.ITM~
        SAY NAME1 @13400
        SAY NAME2 @13408
        SAY UNIDENTIFIED_DESC @13401
        SAY DESC @13409

    COPY_EXISTING ~PBHUNT01.CRE~ ~override~
        REPLACE_CRE_ITEM ~MOAM04~ #0 #0 #0 ~UNSTEALABLE~ ~AMULET~ EQUIP
END

///////////////////////////////////////////////////////////////////////////
// The Ancient Sermon - Assign to Ameralis Zauviir in Watcher's Keep     //
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN
    COPY ~forgotten-armament/itm/MOAM05.ITM~ ~override/MOAM05.ITM~
        SAY NAME1 @13400
        SAY NAME2 @13410
        SAY UNIDENTIFIED_DESC @13401
        SAY DESC @13411

    COPY_EXISTING ~GORWOM04.CRE~ ~override~
        REPLACE_CRE_ITEM ~MOAM05~ #0 #0 #0 ~UNSTEALABLE~ ~AMULET~ EQUIP
END

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Belts                                                                 //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Ceremonial Uthgardt Belt - Assign to Pai'Na                           //
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN
    COPY ~forgotten-armament/itm/MOBL01.ITM~ ~override/MOBL01.ITM~
        SAY NAME1 @13500
        SAY NAME2 @13502
        SAY UNIDENTIFIED_DESC @13501
        SAY DESC @13503

    COPY_EXISTING ~SPPAIN.CRE~ ~override~
        REPLACE_CRE_ITEM ~MOBL01~ #0 #0 #0 ~UNSTEALABLE~ ~BELT~ EQUIP
END

///////////////////////////////////////////////////////////////////////////
// Belt of Agility +2 - Assign to                                  //
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN
    COPY ~forgotten-armament/itm/MOBL02.ITM~ ~override/MOBL02.ITM~
        SAY NAME1 @13500
        SAY NAME2 @13504
        SAY UNIDENTIFIED_DESC @13501
        SAY DESC @13505
END

///////////////////////////////////////////////////////////////////////////
// Grainstone Belt - Assign to Lemzenn at Two-Fold Temple                //
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN
    COPY ~forgotten-armament/itm/MOBL03.ITM~ ~override/MOBL03.ITM~
        SAY NAME1 @13500
        SAY NAME2 @13511
        SAY UNIDENTIFIED_DESC @13501
        SAY DESC @13512

    COPY_EXISTING ~OHRLEMZE.CRE~ ~override~
        REPLACE_CRE_ITEM ~MOBL03~ #0 #0 #0 ~UNSTEALABLE~ ~BELT~ EQUIP
END

///////////////////////////////////////////////////////////////////////////
// Graena's Triumph - Assign to Maferan                                  //
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN
    COPY ~forgotten-armament/itm/MOBL04.ITM~ ~override/MOBL04.ITM~
        SAY NAME1 @13500
        SAY NAME2 @13513
        SAY UNIDENTIFIED_DESC @13501
        SAY DESC @13514

    COPY_EXISTING ~HLMAFER.CRE~ ~override~
        REPLACE_CRE_ITEM ~MOBL04~ #0 #0 #0 ~UNSTEALABLE~ ~BELT~ EQUIP
END

///////////////////////////////////////////////////////////////////////////
// Sash of Shimmering - Assign in BGEE and BG2EE     //
///////////////////////////////////////////////////////////////////////////
COPY ~forgotten-armament/itm/MOBL05.ITM~ ~override/MOBL05.ITM~
    SAY NAME1 @13500
    SAY NAME2 @13515
    SAY UNIDENTIFIED_DESC @13501
    SAY DESC @13516

ACTION_IF (GAME_IS ~bgee eet~) BEGIN
    COPY_EXISTING ~TRACEA.CRE~ ~override~ // Assign to Tracea Carol in fight against Aec'letec
        REPLACE_CRE_ITEM ~MOBL05~ #0 #0 #0 ~UNSTEALABLE~ ~BELT~ EQUIP
END

ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN

END

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Boots                                                                 //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Create Boots of Striding +1 - Assign to                                             //
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN
    COPY ~forgotten-armament/itm/MOBT01.ITM~ ~override/MOBT01.ITM~
        SAY NAME1 @13600
        SAY NAME2 @13604
        SAY UNIDENTIFIED_DESC @13601
        SAY DESC @13605


END

///////////////////////////////////////////////////////////////////////////
// Create Boots of Striding +2 - Assign to Boz in the Underdark          //
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN
    COPY ~forgotten-armament/itm/MOBT02.ITM~ ~override/MOBT02.ITM~
        SAY NAME1 @13600
        SAY NAME2 @13606
        SAY UNIDENTIFIED_DESC @13601
        SAY DESC @13607

    COPY_EXISTING ~GPFIGHT1.CRE~ ~override~
        REPLACE_CRE_ITEM ~MOBT02~ #0 #0 #0 ~UNSTEALABLE~ ~BOOTS~ EQUIP
END

///////////////////////////////////////////////////////////////////////////
// Create Boots of Striding +3 - Assign to                                             //
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN
    COPY ~forgotten-armament/itm/MOBT03.ITM~ ~override/MOBT03.ITM~
        SAY NAME1 @13600
        SAY NAME2 @13608
        SAY UNIDENTIFIED_DESC @13601
        SAY DESC @13609


END

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Cloaks                                                                //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Create Mantle of Gram the Mouse - Assign to                                                  //
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN
    COPY ~forgotten-armament/itm/MOCLK01.ITM~ ~override/MOCLK01.ITM~
        SAY NAME1 @13700
        SAY NAME2 @13704
        SAY UNIDENTIFIED_DESC @13701
        SAY DESC @13705


END

///////////////////////////////////////////////////////////////////////////
// Create Balhodrie's Constant Hearth - Assign to Ketta                  //
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN
    COPY ~forgotten-armament/itm/MOCLK02.ITM~ ~override/MOCLK02.ITM~
        SAY NAME1 @13700
        SAY NAME2 @13706
        SAY UNIDENTIFIED_DESC @13701
        SAY DESC @13707

    COPY_EXISTING ~HLKETTA.CRE~ ~override~
        REPLACE_CRE_ITEM ~MOCLK02~ #0 #0 #0 ~UNSTEALABLE~ ~CLOAK~ EQUIP

    COPY_EXISTING ~HLKETTA2.CRE~ ~override~
        REPLACE_CRE_ITEM ~MOCLK02~ #0 #0 #0 ~UNSTEALABLE~ ~CLOAK~ EQUIP
END

///////////////////////////////////////////////////////////////////////////
// Create A Mad Gent's Cloak - Assign to Chandrilla in Underdark         //
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN
    COPY ~forgotten-armament/itm/MOCLK03.ITM~ ~override/MOCLK03.ITM~
        SAY NAME1 @13700
        SAY NAME2 @13708
        SAY UNIDENTIFIED_DESC @13701
        SAY DESC @13709

    COPY_EXISTING ~GPPRI1.CRE~ ~override~ 
        REPLACE_CRE_ITEM ~MOCLK03~ #0 #0 #0 ~UNSTEALABLE~ ~CLOAK~ EQUIP
END

///////////////////////////////////////////////////////////////////////////
// Create Antimagic Cloak - Assign to                                                  //
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN
    COPY ~forgotten-armament/itm/MOCLK04.ITM~ ~override/MOCLK04.ITM~
        SAY NAME1 @13700
        SAY NAME2 @13710
        SAY UNIDENTIFIED_DESC @13701
        SAY DESC @13711


END

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Gauntlets                                                             //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Create Ysridain's Touch - Assign to                                                  //
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN
    COPY ~forgotten-armament/itm/MOGLV01.ITM~ ~override/MOGLV01.ITM~
        SAY NAME1 @13800
        SAY NAME2 @13804
        SAY UNIDENTIFIED_DESC @13801
        SAY DESC @13805


END

///////////////////////////////////////////////////////////////////////////
// Create Favor of Ilum Lura - Assign to                                                  //
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN
    COPY ~forgotten-armament/itm/MOGLV02.ITM~ ~override/MOGLV02.ITM~
        SAY NAME1 @13800
        SAY NAME2 @13806
        SAY UNIDENTIFIED_DESC @13801
        SAY DESC @13807


END

///////////////////////////////////////////////////////////////////////////
// Create Elder Oak Gloves - Assign to                                                  //
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN
    COPY ~forgotten-armament/itm/MOGLV03.ITM~ ~override/MOGLV03.ITM~
        SAY NAME1 @13800
        SAY NAME2 @13808
        SAY UNIDENTIFIED_DESC @13801
        SAY DESC @13809


END

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Bracers                                                               //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Create Imaskari Bracers of Immortality - Assign to                                          //
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN
    COPY ~forgotten-armament/itm/MOBR01.ITM~ ~override/MOBR01.ITM~
        SAY NAME1 @13900
        SAY NAME2 @13902
        SAY UNIDENTIFIED_DESC @13901
        SAY DESC @13903


END

///////////////////////////////////////////////////////////////////////////
// Create Bracers of Artifice - Assign to                                          //
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN
    COPY ~forgotten-armament/itm/MOBR02.ITM~ ~override/MOBR02.ITM~
        SAY NAME1 @13900
        SAY NAME2 @13904
        SAY UNIDENTIFIED_DESC @13901
        SAY DESC @13905


END

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Helmets                                                               //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Create Helm of Gram the Mouse - Assign to                                          //
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN
    COPY ~forgotten-armament/itm/MOHED01.ITM~ ~override/MOHED01.ITM~
        SAY NAME1 @14000
        SAY NAME2 @14004
        SAY UNIDENTIFIED_DESC @14001
        SAY DESC @14005


END

///////////////////////////////////////////////////////////////////////////
// Create Anagrys' Mindmaze - Assign to                                          //
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN
    COPY ~forgotten-armament/itm/MOHED02.ITM~ ~override/MOHED02.ITM~
        SAY NAME1 @14000
        SAY NAME2 @14006
        SAY UNIDENTIFIED_DESC @14001
        SAY DESC @14007

    COPY_EXISTING ~HLSION.CRE~ ~override~
        REPLACE_CRE_ITEM ~MOHED02~ #0 #0 #0 ~UNSTEALABLE~ ~HELMET~ EQUIP
END

///////////////////////////////////////////////////////////////////////////
// Create The Regal - Assign to                                          //
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN
    COPY ~forgotten-armament/itm/MOHED03.ITM~ ~override/MOHED03.ITM~
        SAY NAME1 @14000
        SAY NAME2 @14008
        SAY UNIDENTIFIED_DESC @14001
        SAY DESC @14009


END

///////////////////////////////////////////////////////////////////////////
// Create Golden Circlet - Assign to                                          //
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN
    COPY ~forgotten-armament/itm/MOHED04.ITM~ ~override/MOHED04.ITM~
        SAY NAME1 @14000
        SAY NAME2 @14010
        SAY UNIDENTIFIED_DESC @14001
        SAY DESC @14011


END

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Rings                                                                 //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Create Bone Ring - Assign to                                                                 //
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN
    COPY ~forgotten-armament/itm/MORNG01.ITM~ ~override/MORNG01.ITM~
        SAY NAME1 @14200
        SAY NAME2 @14204
        SAY UNIDENTIFIED_DESC @14201
        SAY DESC @14205


END

///////////////////////////////////////////////////////////////////////////
// Create Bone Dancer's Ring - Assign to                                                  //
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN
    COPY ~forgotten-armament/itm/MORNG02.ITM~ ~override/MORNG02.ITM~
        SAY NAME1 @14200
        SAY NAME2 @14206
        SAY UNIDENTIFIED_DESC @14201
        SAY DESC @14207

END
