///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Forgotten Armament Improved Spears                                    //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Import Files                                                          //
///////////////////////////////////////////////////////////////////////////
COPY ~forgotten-armament/spl/MOCRS01.SPL~ ~override~ // +1d8 DMG on Crit Strike

///////////////////////////////////////////////////////////////////////////
// Update all Spears                                                      //
///////////////////////////////////////////////////////////////////////////
OUTER_SPRINT spearcrit @11408

COPY_EXISTING_REGEXP GLOB ~^.+\.itm$~ ~override~
  READ_BYTE  0x31 prof
  READ_SHORT 0x1c type

  // Spears
  PATCH_IF (prof = 98) BEGIN
    LPF ALTER_ITEM_HEADER INT_VAR header_type=1 dicesize=8 dicenumber=1 END
    LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 341 target = 1 parameter2 = 1 timing = 2 resist_dispel = 0 probability1 = 100 STR_VAR resource = ~MOSPR01~ END
    PATCH_FOR_EACH offset IN 0x50 0x54 BEGIN
      READ_LONG ~%offset%~ desc_strref
      PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
        READ_STRREF ~%offset%~ desc
        INNER_PATCH_SAVE desc ~%desc%~ BEGIN
          REPLACE_TEXTUALLY ~1d6~ ~1d8~
          REPLACE_TEXTUALLY ~Speed Factor~ ~%spearcrit%~
        END
        SAY_EVALUATED ~%offset%~ ~%desc%~
      END
    END
  END

  BUT_ONLY