// Forgotten Armament - Move Items

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Move Items BG: EE and EET                                             //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bgee eet~) BEGIN

///////////////////////////////////////////////////////////////////////////
// Move Ashideena +2 to Diyab in Iron Throne Building                    //
///////////////////////////////////////////////////////////////////////////
    COPY_EXISTING ~DIYAB.CRE~ ~override~
        REPLACE_CRE_ITEM ~HAMM03~ #0 #0 #0 ~UNSTEALABLE~ ~WEAPON1~ EQUIP

    // Give Bassilis Lesser Rift Hammer else regular +1 warhammer
    ACTION_IF FILE_EXISTS_IN_GAME ~MOHM01.ITM~ BEGIN
        COPY_EXISTING ~BASSIL.CRE~ ~override~
            REPLACE_CRE_ITEM ~MOHM01~ #0 #0 #0 ~UNSTEALABLE~ ~WEAPON1~ EQUIP
    END ELSE BEGIN
        COPY_EXISTING ~BASSIL.CRE~ ~override~
            REPLACE_CRE_ITEM ~HAMM02~ #0 #0 #0 ~UNSTEALABLE~ ~WEAPON1~ EQUIP
    END

///////////////////////////////////////////////////////////////////////////
// Move Varscona +2 to Pargus (Maulers of Undermountain)                 //
///////////////////////////////////////////////////////////////////////////
    COPY_EXISTING ~PARGUS.CRE~ ~override~
        REPLACE_CRE_ITEM ~SW1H06~ #0 #0 #0 ~UNSTEALABLE~ ~WEAPON1~ EQUIP

    // Give Greywolf Spiked Long Sword +1 else regular +1 long sowrd
    ACTION_IF FILE_EXISTS_IN_GAME ~ULSWD2B.ITM~ BEGIN
        COPY_EXISTING ~GREYWO.CRE~ ~override~
            REPLACE_CRE_ITEM ~ULSWD2B~ #0 #0 #0 ~UNSTEALABLE~ ~WEAPON1~ EQUIP
    END ELSE BEGIN
        COPY_EXISTING ~GREYWO.CRE~ ~override~
            REPLACE_CRE_ITEM ~SW1H05~ #0 #0 #0 ~UNSTEALABLE~ ~WEAPON1~ EQUIP
    END

END

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Move Items BGII: EE and EET                                           //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN
    
///////////////////////////////////////////////////////////////////////////
// Move Defender of Easthaven to Mogadish in Planar Sphere               //
///////////////////////////////////////////////////////////////////////////
    COPY_EXISTING ~OBSHAL07.CRE~ ~override~
        SET_BG2_PROFICIENCY ~PROFICIENCYFLAILMORNINGSTAR~ 1
        REPLACE_CRE_ITEM ~WAFLAIL~ #0 #0 #0 ~UNSTEALABLE~ ~WEAPON1~ EQUIP
    COPY_EXISTING ~WMART1.STO~ ~override~
        REMOVE_STORE_ITEM ~WAFLAIL~

END