// Forgotten Armament - Replace Boots of Speed (Paws of the Cheetah)

///////////////////////////////////////////////////////////////////////////
// Boots of Hardiness +1 Replaces                                             //
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN
    COPY ~forgotten-armament/itm/MOBT04.ITM~ ~override/MOBT04.ITM~
        SAY NAME1 @13600
        SAY NAME2 @13610
        SAY UNIDENTIFIED_DESC @13601
        SAY DESC @13611


END

///////////////////////////////////////////////////////////////////////////
// Boots of Hardiness +2 Replaces                                             //
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN
    COPY ~forgotten-armament/itm/MOBT05.ITM~ ~override/MOBT05.ITM~
        SAY NAME1 @13600
        SAY NAME2 @13612
        SAY UNIDENTIFIED_DESC @13601
        SAY DESC @13613


END

///////////////////////////////////////////////////////////////////////////
// Boots of Hardiness +3 Replaces                                             //
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN
    COPY ~forgotten-armament/itm/MOBT06.ITM~ ~override/MOBT06.ITM~
        SAY NAME1 @13600
        SAY NAME2 @13614
        SAY UNIDENTIFIED_DESC @13601
        SAY DESC @13615


END