// Forgotten Armament - Update Strength Items

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Increment Items                                                       //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
COPY_EXISTING_REGEXP GLOB ~^.+\.itm$~ ~override~
PATCH_IF (%SOURCE_SIZE% > 0x71) BEGIN
    GET_OFFSET_ARRAY ab_array ITM_V10_HEADERS
    PHP_EACH ab_array AS int => ab_off BEGIN
    GET_OFFSET_ARRAY2 fx_array ab_off ITM_V10_HEAD_EFFECTS
    PHP_EACH fx_array AS int => fx_off BEGIN
        READ_SHORT fx_off fx_type
        PATCH_IF fx_type = 44 BEGIN
            READ_LONG (fx_off + 0x04) fx_param1
            PATCH_IF fx_param1 = 19 BEGIN
                LPF ALTER_EFFECT INT_VAR match_opcode = 44 parameter1 = 2 parameter2 = 0 END

                PATCH_FOR_EACH offset IN 0x50 0x54 BEGIN
                READ_LONG ~%offset%~ desc_strref
                    PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
                      READ_STRREF ~%offset%~ desc
                      INNER_PATCH_SAVE desc ~%desc%~ BEGIN
                        REPLACE_TEXTUALLY ~19~ ~+2~
                      END
                    END
                END                
            END
        END
    END
    END
END



/*
SPRINT source ~%SOURCE_FILE%~
READ_LONG 0x6a fx_off ELSE 0
READ_SHORT 0x6e fx_num ELSE 0
//READ_LONG fx_off fx_type
READ_BYTE 0x33 fx_type ELSE 2

FOR (index = 0 ; index < fx_num ; ++index) BEGIN
  READ_SHORT (fx_off        + (0x08 * fx_type) + (index * (0x30 + (0xd8 * fx_type)))) opcode
  
  PATCH_IF (opcode = 44) BEGIN
    READ_LONG  (fx_off + 0x04 + (0x10 * fx_type) + (index * (0x30 + (0xd8 * fx_type)))) strength

    PATCH_IF (strength = 18) BEGIN
        LPF ALTER_EFFECT INT_VAR match_opcode = 44 parameter1 = 1 parameter2 = 0 END

        PATCH_FOR_EACH offset IN 0x50 0x54 BEGIN
        READ_LONG ~%offset%~ desc_strref
            PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
              READ_STRREF ~%offset%~ desc
              INNER_PATCH_SAVE desc ~%desc%~ BEGIN
                REPLACE_TEXTUALLY ~18/00~ ~+1~
              END
            END
        END
    END ELSE PATCH_IF (strength = 19) BEGIN
        LPF ALTER_EFFECT INT_VAR match_opcode = 44 parameter1 = 2 parameter2 = 0 END

        PATCH_FOR_EACH offset IN 0x50 0x54 BEGIN
        READ_LONG ~%offset%~ desc_strref
            PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
              READ_STRREF ~%offset%~ desc
              INNER_PATCH_SAVE desc ~%desc%~ BEGIN
                REPLACE_TEXTUALLY ~19~ ~+2~
              END
            END
        END
    END
  END
END
BUT_ONLY
*/
/*
///////////////////////////////////////////////////////////////////////////
// Girdle of Hill Giant Strength +2 STR                                  //
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN
    COPY ~forgotten-armament/itm/BELT06.ITM~ ~override/BELT06.ITM~
        SAY DESC @13506
END

///////////////////////////////////////////////////////////////////////////
// Girdle of Stone Giant Strength +3 STR                                 //
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN
    COPY ~forgotten-armament/itm/BELT07.ITM~ ~override/BELT07.ITM~
        SAY DESC @13507
END

///////////////////////////////////////////////////////////////////////////
// Girdle of Frost Giant Strength +4 STR                                 //
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN
    COPY ~forgotten-armament/itm/BELT08.ITM~ ~override/BELT08.ITM~
        SAY DESC @13508
END

///////////////////////////////////////////////////////////////////////////
// Girdle of Fire Giant Strength +5 STR                                  //
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN
    COPY ~forgotten-armament/itm/BELT11.ITM~ ~override/BELT11.ITM~
        SAY DESC @13509
END

///////////////////////////////////////////////////////////////////////////
// Girdle of Fortitude +4 CON                                            //
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN
    COPY ~forgotten-armament/itm/BELT09.ITM~ ~override/BELT09.ITM~
        SAY DESC @13510
END

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Gauntlets                                                             //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Hands of Takkok +1 STR                                                //
///////////////////////////////////////////////////////////////////////////
COPY ~forgotten-armament/itm/BRAC06.ITM~ ~override/BRAC06.ITM~
    SAY DESC @13802

///////////////////////////////////////////////////////////////////////////
// The Brawling Hands +2 DEX                                             //
///////////////////////////////////////////////////////////////////////////
COPY ~forgotten-armament/itm/BRAC07.ITM~ ~override/BRAC07.ITM~
    SAY DESC @13803

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Rings                                                                 //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Ring of Human Influence (+2 CHA)                                      //
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN
    COPY ~forgotten-armament/itm/RING30.ITM~ ~override/RING30.ITM~
        SAY DESC @14202
END

///////////////////////////////////////////////////////////////////////////
// Lord Foreshadow's Ring of Human Influence (+2 CHA)                    //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~X#RINGRO.itm~ BEGIN
    COPY ~forgotten-armament/itm/X#RINGRO.itm~ ~override/X#RINGRO.itm~
        SAY DESC @14203
END

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Weapons                                                               //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Angurvadal +4 (+5 STR Temp)                                           //
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN
    COPY ~forgotten-armament/itm/SW1H60.ITM~ ~override/SW1H60.ITM~
        SAY DESC @10702
END

///////////////////////////////////////////////////////////////////////////
// Angurvadal +5 (+5 STR)                                                //
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN
    COPY ~forgotten-armament/itm/SW1H61.ITM~ ~override/SW1H61.ITM~
        SAY DESC @10703
END

///////////////////////////////////////////////////////////////////////////
// Crom Faeyr +5 (+8 STR)                                                //
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN
    COPY ~forgotten-armament/itm/HAMM09.ITM~ ~override/HAMM09.ITM~
        SAY DESC @11704
END

///////////////////////////////////////////////////////////////////////////
// Mauler's Arm +2 (+1 STR)                                              //
///////////////////////////////////////////////////////////////////////////
ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN
    COPY ~forgotten-armament/itm/BLUN19.ITM~ ~override/BLUN19.ITM~
        SAY DESC @10802
END
*/