// Forgotten Armament - Update Existing Items

/*************************************************************************/
///////////////////////////////////////////////////////////////////////////
// UPDATE MELEE WEAPONS                                                  //
///////////////////////////////////////////////////////////////////////////
/*************************************************************************/

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Axe                                                                   //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Mauletar +2                                                           //
// Fear Immunity                                                         //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~AX1H03.ITM~ BEGIN
    COPY ~forgotten-armament/itm/update/AX1H03.ITM~ ~override~
        SAY NAME1 @10000
        SAY NAME2 @30000
        SAY UNIDENTIFIED_DESC @10001
        SAY DESC @30001
END

///////////////////////////////////////////////////////////////////////////
// Azuredge                                                              //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~AX1H10.ITM~ BEGIN
    COPY ~forgotten-armament/itm/update/AX1H10.ITM~ ~override~
END

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Dagger                                                                //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Dagger of <CHARNAME>                                                  //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~DAGG19.ITM~ BEGIN
OUTER_SPRINT olddagger1 @30300
OUTER_SPRINT olddagger2 @30302
OUTER_SPRINT newdagger1 @30301
OUTER_SPRINT newdagger2 @30303

    COPY_EXISTING ~DAGG19.ITM~ ~override~
        WRITE_LONG 0x60 2
        LPF ALTER_ITEM_HEADER INT_VAR header_type=1 thac0_bonus = 2 damage_bonus = 2 END
        LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 142 target = 1 parameter2 = 63 timing = 2 resist_dispel = 2 probability1 = 100 END 
        LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 166 target = 1 parameter1 = 10 parameter2 = 0 timing = 2 resist_dispel = 0 probability1 = 100 END 
        LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 42 target = 1 parameter1 = 10 parameter2 = 2 timing = 2 resist_dispel = 0 probability1 = 100 END
        LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 42 target = 1 parameter1 = 10 parameter2 = 1 timing = 2 resist_dispel = 0 probability1 = 100 END
        LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 42 target = 1 parameter1 = 10 parameter2 = 0 timing = 2 resist_dispel = 0 probability1 = 100 END 

        READ_LONG 0x50 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x50 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%olddagger1%~ ~%newdagger1%~
              REPLACE_TEXTUALLY ~%olddagger2%~ ~%newdagger2%~
            END
            SAY_EVALUATED 0x50 ~%desc%~
          END
END

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Flails                                                                //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Flail of Ages +5                                                      //
// Remove Magic Resistance and Free Action                               //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~BLUN30.ITM~ BEGIN
OUTER_SPRINT oldflail1 @30400

    COPY_EXISTING ~BLUN30.ITM~ ~override~
        LPF DELETE_ITEM_EQEFFECT INT_VAR opcode_to_delete = 46 END
        LPF DELETE_ITEM_EQEFFECT INT_VAR opcode_to_delete = 267 END
        LPF DELETE_ITEM_EQEFFECT INT_VAR opcode_to_delete = 142 END
        LPF DELETE_ITEM_EQEFFECT INT_VAR opcode_to_delete = 163 END
        LPF DELETE_ITEM_EQEFFECT INT_VAR opcode_to_delete = 101 END
        LPF DELETE_ITEM_EQEFFECT INT_VAR opcode_to_delete = 296 END
        LPF DELETE_ITEM_EQEFFECT INT_VAR opcode_to_delete = 166 END
        LPF DELETE_ITEM_EQEFFECT INT_VAR opcode_to_delete = 126 END
        LPF DELETE_ITEM_EQEFFECT INT_VAR opcode_to_delete = 169 END
        LPF DELETE_ITEM_EQEFFECT INT_VAR opcode_to_delete = 206 END
        LPF DELETE_ITEM_EQEFFECT INT_VAR opcode_to_delete = 162 END
        LPF DELETE_ITEM_EQEFFECT INT_VAR opcode_to_delete = 240 END

        READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldflail1%~ ~~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
END

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Halberd                                                               //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Suryris Blade                                                         //
// AC -1                                                                 //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~HALB03.ITM~ BEGIN
OUTER_SPRINT oldhalb1 @30500
OUTER_SPRINT newhalb1 @30501

    COPY_EXISTING ~HALB03.ITM~ ~override~
        LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 0 target = 1 parameter1 = 1 parameter2 = 0 timing = 2 resist_dispel = 2 probability1 = 100 END

        READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldhalb1%~ ~%newhalb1%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
END

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Katana                                                                //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Crimson Dawn                                                          //
// +3 item                                                               //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~BDSW1H01.ITM~ BEGIN
OUTER_SPRINT oldkata4 @30606
OUTER_SPRINT newkata4 @30607

    COPY_EXISTING ~BDSW1H01.ITM~ ~override~
      WRITE_LONG 0x60 3
      LPF ALTER_ITEM_HEADER INT_VAR header_type=1 thac0_bonus = 3 damage_bonus = 3 END

      PATCH_FOR_EACH offset IN 0xc 0x54 BEGIN
        READ_LONG ~%offset%~ desc_strref
            PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
              READ_STRREF ~%offset%~ desc
              INNER_PATCH_SAVE desc ~%desc%~ BEGIN
                REPLACE_TEXTUALLY ~%oldkata4%~ ~%newkata4%~
              END
              SAY_EVALUATED ~%offset%~ ~%desc%~
            END
      END
END

///////////////////////////////////////////////////////////////////////////
// Hindo's Doom +3                                                       //
// 2d10+6 vs undead                                                      //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~SW1H70.ITM~ BEGIN
COPY ~forgotten-armament/eff/update_item/MO1H70.EFF~ ~override~
OUTER_SPRINT oldkata1 @30600
OUTER_SPRINT newkata1 @30601
    
    COPY_EXISTING ~SW1H70.ITM~ ~override~
        LPF ADD_ITEM_EFFECT INT_VAR opcode = 177 type = 1 target = 2 parameter1 = 4 parameter2 = 3 timing = 1 resist_dispel = 0 probability1 = 100 STR_VAR resource = ~mo1h70~ END

        READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldkata1%~ ~%newkata1%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
END

///////////////////////////////////////////////////////////////////////////
// Hindo's Doom +4                                                       //
// 2d10+8 vs undead, save vs -4 or be destroyed                          //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~SW1H71.ITM~ BEGIN
COPY ~forgotten-armament/eff/update_item/MO1H71.EFF~ ~override~
OUTER_SPRINT oldkata2 @30602
OUTER_SPRINT newkata2 @30603
OUTER_SPRINT oldkata3 @30604
OUTER_SPRINT newkata3 @30605
    
    COPY_EXISTING ~SW1H71.ITM~ ~override~
        LPF ADD_ITEM_EFFECT INT_VAR opcode = 177 type = 1 target = 2 parameter1 = 4 parameter2 = 3 timing = 1 resist_dispel = 0 probability1 = 100 STR_VAR resource = ~mesdie~ END
        LPF ADD_ITEM_EFFECT INT_VAR opcode = 177 type = 1 target = 2 parameter1 = 4 parameter2 = 3 timing = 1 resist_dispel = 0 probability1 = 100 STR_VAR resource = ~die~ END
        LPF ADD_ITEM_EFFECT INT_VAR opcode = 177 type = 1 target = 2 parameter1 = 4 parameter2 = 3 timing = 1 resist_dispel = 0 probability1 = 100 STR_VAR resource = ~mo1h71~ END

        READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldkata2%~ ~%newkata2%~
              REPLACE_TEXTUALLY ~%oldkata3%~ ~%newkata3%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
END

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Long Sword                                                            //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Blackrazor                                                            //
// +4 weapon                                                             //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~MISCBC.ITM~ BEGIN
OUTER_SPRINT oldlong1 @30700
OUTER_SPRINT newlong1 @30701

    COPY_EXISTING ~MISCBC.ITM~ ~override~
      WRITE_LONG 0x60 4
      LPF ALTER_ITEM_HEADER INT_VAR header_type=1 thac0_bonus = 4 damage_bonus = 4 END

      PATCH_FOR_EACH offset IN 0x8 0xc 0x54 BEGIN
        READ_LONG ~%offset%~ desc_strref
            PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
              READ_STRREF ~%offset%~ desc
              INNER_PATCH_SAVE desc ~%desc%~ BEGIN
                REPLACE_TEXTUALLY ~%oldlong1%~ ~%newlong1%~
              END
              SAY_EVALUATED ~%offset%~ ~%desc%~
            END
      END
END

///////////////////////////////////////////////////////////////////////////
// Daystar                                                               //
// +3 weapon                                                             //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~SW1H31.ITM~ BEGIN
OUTER_SPRINT oldlong2 @30702
OUTER_SPRINT newlong2 @30703

    COPY_EXISTING ~SW1H31.ITM~ ~override~
      WRITE_LONG 0x60 3
      LPF ALTER_ITEM_HEADER INT_VAR header_type=1 thac0_bonus = 3 damage_bonus = 3 END

      PATCH_FOR_EACH offset IN 0xc 0x54 BEGIN
        READ_LONG ~%offset%~ desc_strref
            PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
              READ_STRREF ~%offset%~ desc
              INNER_PATCH_SAVE desc ~%desc%~ BEGIN
                REPLACE_TEXTUALLY ~%oldlong2%~ ~%newlong2%~
              END
              SAY_EVALUATED ~%offset%~ ~%desc%~
            END
      END
END

///////////////////////////////////////////////////////////////////////////
// Angurvadal +5                                                         //    
// Needs more oomph                                                      //
///////////////////////////////////////////////////////////////////////////


///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Mace                                                                  //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Ardulia's Fall                                                        //
// Better save vs hit, +3 weapon, +2 wisdom                              //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~BLUN20.ITM~ BEGIN
OUTER_SPRINT oldmace1 @30800
OUTER_SPRINT newmace1 @30801
OUTER_SPRINT oldmace2 @30802
OUTER_SPRINT newmace2 @30803
OUTER_SPRINT oldmace3 @30804
OUTER_SPRINT newmace3 @30805
OUTER_SPRINT oldmace5 @30808
OUTER_SPRINT newmace5 @30809

    COPY_EXISTING ~BLUN20.ITM~ ~override~
      WRITE_LONG 0x60 3
      LPF ALTER_ITEM_HEADER INT_VAR header_type=1 thac0_bonus = 3 damage_bonus = 3 END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 49 target = 1 parameter1 = 2 parameter2 = 0 timing = 2 resist_dispel = 2 probability1 = 100 END
      LPF ALTER_ITEM_EFFECT INT_VAR match_opcode = 0 check_headers = 1 savebonus = ~-2~ END
      LPF ALTER_ITEM_EFFECT INT_VAR match_opcode = 54 check_headers = 1 savebonus = ~-2~ END
      LPF ALTER_ITEM_EFFECT INT_VAR match_opcode = 142 check_headers = 1 savebonus = ~-2~ END
      LPF ALTER_ITEM_EFFECT INT_VAR match_opcode = 139 check_headers = 1 savebonus = ~-2~ END
      LPF ALTER_ITEM_EFFECT INT_VAR match_opcode = 141 check_headers = 1 savebonus = ~-2~ END
      LPF ALTER_ITEM_EFFECT INT_VAR match_opcode = 174 check_headers = 1 savebonus = ~-2~ END
      LPF ALTER_ITEM_EFFECT INT_VAR match_opcode = 40 check_headers = 1 savebonus = ~-2~ END

      PATCH_FOR_EACH offset IN 0xc 0x54 BEGIN
        READ_LONG ~%offset%~ desc_strref
            PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
              READ_STRREF ~%offset%~ desc
              INNER_PATCH_SAVE desc ~%desc%~ BEGIN
                REPLACE_TEXTUALLY ~%oldmace5%~ ~%newmace5%~
                REPLACE_TEXTUALLY ~%oldmace1%~ ~%newmace1%~
                REPLACE_TEXTUALLY ~%oldmace2%~ ~%newmace2%~
                REPLACE_TEXTUALLY ~%oldmace3%~ ~%newmace3%~
              END
              SAY_EVALUATED ~%offset%~ ~%desc%~
            END
      END
END

///////////////////////////////////////////////////////////////////////////
// Krotan's Skullcrusher                                                 //
// +5% crit strike for this weapon                                       //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~BLUN11.ITM~ BEGIN
OUTER_SPRINT oldmace4 @30806
OUTER_SPRINT newmace4 @30807

    COPY_EXISTING ~BLUN11.ITM~ ~override~
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 301 target = 1 parameter1 = 1 parameter2 = 1 timing = 2 resist_dispel = 0 probability1 = 100 END

      READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldmace4%~ ~%newmace4%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
END

///////////////////////////////////////////////////////////////////////////
// Storm Star +5                                                         //
// +2d6 electrical damage                                                //
// 10% chance of chain lightning                                         //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~BLUN29.ITM~ BEGIN
OUTER_SPRINT oldmace6 @30810
OUTER_SPRINT newmace6 @30811
OUTER_SPRINT oldmace7 @30812
OUTER_SPRINT newmace7 @30813

    COPY_EXISTING ~BLUN29.ITM~ ~override~
      LPF ALTER_ITEM_EFFECT INT_VAR match_opcode = 146 check_headers = 1 probability1 = 10 END
      LPF ALTER_ITEM_EFFECT INT_VAR match_opcode = 12 check_headers = 1 dicenumber = 2 END

      READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldmace6%~ ~%newmace6%~
              REPLACE_TEXTUALLY ~%oldmace7%~ ~%newmace7%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
END

///////////////////////////////////////////////////////////////////////////
// Skullcrusher                                                          //
// +10% crit strike with this weapon                                     //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~BLUN18.ITM~ BEGIN
OUTER_SPRINT oldmace8 @30814
OUTER_SPRINT newmace8 @30815
    
    COPY_EXISTING ~BLUN18.ITM~ ~override~
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 301 target = 1 parameter1 = 2 parameter2 = 1 timing = 2 resist_dispel = 0 probability1 = 100 END

      READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldmace8%~ ~%newmace8%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
END

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Scimitar                                                              //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Rashad Talon                                                          //
// +1d6 Slashing on Crit                                                 //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~SW1H23.ITM~ BEGIN
COPY ~forgotten-armament/eff/update_item/MO1H23.EFF~ ~override~
OUTER_SPRINT oldscimi1 @31200
OUTER_SPRINT newscimi1 @31201

    COPY_EXISTING ~SW1H23.ITM~ ~override~
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 341 target = 1 parameter1 = 1 parameter2 = 1 timing = 2 resist_dispel = 0 probability1 = 100 STR_VAR resource = ~mo1h23~ END

      READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldscimi1%~ ~%newscimi1%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
END

///////////////////////////////////////////////////////////////////////////
// Spectral Brand +5                                                     //
// Replace Piercing Strike with Critical Strike                          //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~SW1H69.ITM~ BEGIN
OUTER_SPRINT oldscimi2 @31202
OUTER_SPRINT newscimi2 @31203
OUTER_SPRINT oldscimi3 @31204
OUTER_SPRINT newscimi3 @31205
OUTER_SPRINT oldscimi4 @31206
OUTER_SPRINT newscimi4 @31207

    COPY_EXISTING ~SW1H69.ITM~ ~override~
      LPF ALTER_ITEM_EFFECT INT_VAR match_opcode = 142 check_headers = 1 parameter2 = 152 duration = 6 END
      LPF ALTER_ITEM_EFFECT INT_VAR match_opcode = 54 check_headers = 1 new_opcode = 301 parameter1 = 20 duration = 6 END
      LPF ALTER_ITEM_EFFECT INT_VAR match_opcode = 215 check_headers = 1 target = 2 STR_VAR resource = ~sppowatk~ END
      LPF CLONE_EFFECT INT_VAR match_opcode = 301 opcode = 282 parameter2 = 3 END
      LPF CLONE_EFFECT INT_VAR match_opcode = 142 opcode = 174 timing = 1 duration = 0 STR_VAR resource = ~eff_p82~ END
      LPF CLONE_EFFECT INT_VAR match_opcode = 142 opcode = 174 timing = 4 duration = 12 STR_VAR resource = ~eff_e01~ END

      READ_LONG 0x64 hf //Extended header offset
      READ_SHORT 0x68 hc //Extended header count
      FOR (i1 = 0; i1 < hc; i1 += 1) BEGIN //Cycle through headers
        READ_BYTE (0x38 * i1 + hf) pt //Attack type
        PATCH_IF pt = 3 BEGIN
          READ_ASCII (0x38 * i1 + hf + 4) icon
          PATCH_IF ("%icon%" STRING_EQUAL_CASE "SPPR313B") BEGIN
            WRITE_ASCII (0x38 * i1 + hf + 4) ~spcl905b~ #8
          END
        END
      END

      READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldscimi2%~ ~%newscimi2%~
              REPLACE_TEXTUALLY ~%oldscimi3%~ ~%newscimi3%~
              REPLACE_TEXTUALLY ~%oldscimi4%~ ~%newscimi4%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
    
    ACTION_GET_STRREF ~70621~ pierce_strike

    OUTER_PATCH_SAVE pierce_strike ~%pierce_strike%~ BEGIN
      REPLACE_TEXTUALLY ~%oldscimi2%~ ~%newscimi2%~
    END

    STRING_SET_EVALUATE ~70621~ ~%pierce_strike%~
END

///////////////////////////////////////////////////////////////////////////
// Water's Edge +3                                                       //
// +5% crit chance with this weapon                                      //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~SW1H52.ITM~ BEGIN
OUTER_SPRINT oldscimi5 @31208
OUTER_SPRINT newscimi5 @31209

    COPY_EXISTING ~SW1H52.ITM~ ~override~
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 301 target = 1 parameter1 = 1 parameter2 = 1 timing = 2 resist_dispel = 0 probability1 = 100 END

      READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldscimi5%~ ~%newscimi5%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
END

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Short Sword                                                           //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Cutthroat +4                                                          //
// Inflicts 2 points of bleeding damage per hit (one point per round)    //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~SW1H28.ITM~ BEGIN
OUTER_SPRINT oldshort1 @31300
OUTER_SPRINT newshort1 @31301

    COPY_EXISTING ~SW1H28.ITM~ ~override~
      LPF ADD_ITEM_EFFECT INT_VAR opcode = 146 type = 1 target = 2 parameter1 = 1 parameter2 = 1 timing = 1 resist_dispel = 0 probability1 = 100 STR_VAR resource = ~bdsw1h21~ END

      READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldshort1%~ ~%newshort1%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
END

///////////////////////////////////////////////////////////////////////////
// Short Sword of Mask                                                   //
// Non-Detection, Remove Level Drain, 5% chance of proccing assassination//
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~SW1H58.ITM~ AND FILE_EXISTS_IN_GAME ~SW1H59.ITM~ BEGIN
OUTER_SPRINT oldshort2 @31302
OUTER_SPRINT newshort2 @31303
OUTER_SPRINT oldshort3 @31304
OUTER_SPRINT newshort3 @31305

    COPY_EXISTING ~SW1H58.ITM~ ~override~
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 69 target = 1 timing = 2 resist_dispel = 0 probability1 = 100 END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 142 target = 1 parameter2 = 31 timing = 2 resist_dispel = 0 probability1 = 100 END

      READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldshort2%~ ~%newshort2%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END

    COPY_EXISTING ~SW1H59.ITM~ ~override~
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 69 target = 1 timing = 2 resist_dispel = 0 probability1 = 100 END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 142 target = 1 parameter2 = 31 timing = 2 resist_dispel = 0 probability1 = 100 END
      LPF DELETE_EFFECT INT_VAR header_type = 1 match_opcode = 139 END
      LPF DELETE_EFFECT INT_VAR header_type = 1 match_opcode = 216 END
      LPF DELETE_EFFECT INT_VAR header_type = 1 match_opcode = 141 END
      LPF ADD_ITEM_EFFECT INT_VAR opcode = 303 type = 1 target = 1 parameter2 = 1 timing = 0 resist_dispel = 2 duration = 6 probability1 = 100 probability2 = 94 END
      LPF ADD_ITEM_EFFECT INT_VAR opcode = 142 type = 1 target = 1 parameter2 = 156 timing = 0 resist_dispel = 2 duration = 6 probability1 = 100 probability2 = 94 END
      LPF ADD_ITEM_EFFECT INT_VAR opcode = 282 type = 1 target = 1 parameter1 = 4 parameter2 = 3 timing = 0 resist_dispel = 2 duration = 6 probability1 = 100 probability2 = 94 END
      LPF ADD_ITEM_EFFECT INT_VAR opcode = 174 type = 1 target = 1 timing = 4 resist_dispel = 2 duration = 6 probability1 = 100 probability2 = 94 STR_VAR resource = ~eff_e01~ END
      LPF ADD_ITEM_EFFECT INT_VAR opcode = 174 type = 1 target = 1 timing = 1 resist_dispel = 2 duration = 0 probability1 = 100 probability2 = 94 STR_VAR resource = ~wwattack~ END
      LPF ADD_ITEM_EFFECT INT_VAR opcode = 215 type = 1 target = 2 parameter2 = 0 timing = 1 resist_dispel = 0 duration = 0 probability1 = 100 probability2 = 94 STR_VAR resource = ~spgrwhrl~ END

      READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldshort2%~ ~%newshort2%~
              REPLACE_TEXTUALLY ~%oldshort3%~ ~%newshort3%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
END

///////////////////////////////////////////////////////////////////////////
// The Shadow's Blade +3                                                 //
// Luck +1, +1 Backstab (Thieves only)                                   //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~SW1H10.ITM~ BEGIN
COPY ~forgotten-armament/eff/update_item/MO1H10.EFF~ ~override~
OUTER_SPRINT oldshort4 @31306
OUTER_SPRINT newshort4 @31307

    COPY_EXISTING ~SW1H10.ITM~ ~override~
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 22 target = 1 parameter1 = 1 parameter2 = 0 timing = 2 resist_dispel = 0 probability1 = 100 END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 177 target = 1 parameter1 = 205 parameter2 = 5 timing = 2 resist_dispel = 0 probability1 = 100 STR_VAR resource = ~mo1h10~ END

      READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldshort4%~ ~%newshort4%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
END

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Spear                                                                 //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Two-Handed Sword                                                      //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Carsomyr +5/+6                                                        //
// MR increments instead of sets                                         //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~SW2H10.ITM~ AND FILE_EXISTS_IN_GAME ~SW2H19.ITM~ BEGIN
OUTER_SPRINT oldtwohand1 @31500
OUTER_SPRINT newtwohand1 @31501

    ACTION_FOR_EACH carsomyr IN 10 19 BEGIN
      COPY_EXISTING ~SW2H%carsomyr%.ITM~ ~override~ 
        LPF ALTER_ITEM_EFFECT INT_VAR check_globals = 1 match_opcode = 166 parameter2 = 0 END

        READ_LONG 0x54 desc_strref
            PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
              READ_STRREF 0x54 desc
              INNER_PATCH_SAVE desc ~%desc%~ BEGIN
                REPLACE_TEXTUALLY ~%oldtwohand1%~ ~%newtwohand1%~
              END
              SAY_EVALUATED 0x54 ~%desc%~
            END
    END
END

///////////////////////////////////////////////////////////////////////////
// Ir'revrykal                                                           //
// Remove Dispel on Hit and Immunity to Charm                            //
// Add vorpal strike and healing per hit                                 //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~OHREAVER.ITM~ BEGIN
OUTER_SPRINT oldtwohand2 @31502
OUTER_SPRINT newtwohand2 @31503
OUTER_SPRINT vorpal1     @31504

    COPY_EXISTING ~OHREAVER.ITM~ ~override~
      LPF ADD_ITEM_EFFECT INT_VAR opcode = 12 type = 1 parameter1 = 5 parameter2 = 4194304 timing = 1 resist_dispel = 0 probability1 = 100 special = 1 END
      LPF ADD_ITEM_EFFECT INT_VAR opcode = 139 type = 1 target = 2 timing = 9 resist_dispel = 2 probability1 = 10 savingthrow = 3 savebonus = ~-4~ STR_VAR parameter1 = ~%vorpal1%~ END
      LPF ADD_ITEM_EFFECT INT_VAR opcode = 13 type = 1 target = 2 parameter1 = 0 parameter2 = 3 timing = 1 resist_dispel = 2 probability1 = 10 savingthrow = 3 savebonus = ~-4~ END
      LPF ADD_ITEM_EFFECT INT_VAR opcode = 141 type = 1 target = 2 parameter1 = 0 parameter2 = 39 timing = 1 resist_dispel = 2 probability1 = 10 savingthrow = 3 savebonus = ~-4~ END

      READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldtwohand2%~ ~%newtwohand2%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
END

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Wakizashi                                                             //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Yamato +4                                                             //
// +1 APR                                                                //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~SW1H66.ITM~ BEGIN
OUTER_SPRINT oldyamato @31600
OUTER_SPRINT newyamato @31601

    COPY_EXISTING ~SW1H66.ITM~ ~override~ 
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 1 target = 1 parameter1 = 1 parameter2 = 0 timing = 2 resist_dispel = 0 probability1 = 100 END

      READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldyamato%~ ~%newyamato%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
END

///////////////////////////////////////////////////////////////////////////
// Kachiko's Wakizashi +3                                                //
// Increase duration of drain from round to turns                        //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~WAWAK.ITM~ BEGIN
OUTER_SPRINT oldwaki1 @31602
OUTER_SPRINT newwaki1 @31603

    COPY_EXISTING ~WAWAK.ITM~ ~override~ 
      LPF ALTER_ITEM_EFFECT INT_VAR match_opcode = 142 check_headers = 1 duration = 120 END
      LPF ALTER_ITEM_EFFECT INT_VAR match_opcode = 49 check_headers = 1 duration = 120 END

      READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldwaki1%~ ~%newwaki1%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
END

// Dorn 2h make vorpal
// Silver Sword look at legacy stuff
// Usuno no oomph
// Dakkon Zerth 5% chance per hit of restoring a spell
// Bracers: Mintassan's Miraculous Bracers, Red Guard, Clasps of the Devoted, Bracers of the Inner Planes