// Forgotten Armament - Update Existing Items

/*************************************************************************/
///////////////////////////////////////////////////////////////////////////
// UPDATE MELEE WEAPONS                                                  //
///////////////////////////////////////////////////////////////////////////
/*************************************************************************/

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Axe                                                                   //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Mauletar +2                                                           //
// Fear Immunity                                                         //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~AX1H03.ITM~ BEGIN
OUTER_SPRINT oldaxe4 @30000
OUTER_SPRINT newaxe4 @30001
OUTER_SET panic = RESOLVE_STR_REF (@30008)
OUTER_SET morale = RESOLVE_STR_REF (@30009)

    COPY_EXISTING ~AX1H03.ITM~ ~override~
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 267 target = 1 parameter1 = ~%panic%~ timing = 2 resist_dispel = 2 probability1 = 100 END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 267 target = 1 parameter1 = ~%morale%~ timing = 2 resist_dispel = 2 probability1 = 100 END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 142 target = 1 parameter2 = 37 timing = 2 resist_dispel = 2 probability1 = 100 END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 101 target = 1 parameter2 = 24 timing = 2 resist_dispel = 2 probability1 = 100 END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 101 target = 1 parameter2 = 23 timing = 2 resist_dispel = 2 probability1 = 100 END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 101 target = 1 parameter2 = 106 timing = 2 resist_dispel = 2 probability1 = 100 END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 296 target = 1 timing = 2 resist_dispel = 2 probability1 = 100 STR_VAR resource = ~cdhorror~END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 106 target = 1 parameter1 = 1 parameter2 = 1 timing = 2 resist_dispel = 2 probability1 = 100 END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 169 target = 1 parameter2 = 36 timing = 2 resist_dispel = 2 probability1 = 100 END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 161 target = 1 timing = 2 resist_dispel = 2 probability1 = 100 END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 240 target = 1 parameter2 = 36 timing = 2 resist_dispel = 2 probability1 = 100 END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 23 target = 1 timing = 2 resist_dispel = 2 probability1 = 100 END

      READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldaxe4%~ ~%newaxe4%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
END

///////////////////////////////////////////////////////////////////////////
// Azuredge                                                              //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~AX1H10.ITM~ BEGIN
    COPY ~forgotten-armament/itm/update/AX1H10.ITM~ ~override~
END

///////////////////////////////////////////////////////////////////////////
// Frostreaver +3                                                        //
// +2 cold and acid damage (previously +1)                               //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~AX1H13.ITM~ BEGIN
OUTER_SPRINT oldaxe1 @30002
OUTER_SPRINT newaxe1 @30003

    COPY_EXISTING ~AX1H13.ITM~ ~override~
      LPF ALTER_ITEM_EFFECT INT_VAR check_headers = 1 match_opcode = 12 parameter1 = 2 END

      READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldaxe1%~ ~%newaxe1%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
END

///////////////////////////////////////////////////////////////////////////
// Stonefire +3                                                          //
// +1d6 fire damage (previously +2)                                      //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~AX1H12.ITM~ BEGIN
OUTER_SPRINT oldaxe2 @30004
OUTER_SPRINT newaxe2 @30005

    COPY_EXISTING ~AX1H12.ITM~ ~override~
      LPF ALTER_ITEM_EFFECT INT_VAR check_headers = 1 match_opcode = 12 parameter1 = 0 dicenumber = 1 dicesize = 6 END

      READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldaxe2%~ ~%newaxe2%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
END

///////////////////////////////////////////////////////////////////////////
// Chill Axe +2                                                          //
// +1d4 cold damage (previously +1)                                      //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~BDAX1H03.ITM~ BEGIN
OUTER_SPRINT oldaxe3 @30006
OUTER_SPRINT newaxe3 @30007

    COPY_EXISTING ~BDAX1H03.ITM~ ~override~
      LPF ALTER_ITEM_EFFECT INT_VAR check_headers = 1 match_opcode = 12 parameter1 = 0 dicenumber = 1 dicesize = 4 END

      READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldaxe3%~ ~%newaxe3%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
END

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Bastard Sword                                                         //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Blade of Searing +3                                                   //
// +1d6 fire damage (previously +1)                                      //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~SW1H39.ITM~ BEGIN
OUTER_SPRINT oldbast1 @30100
OUTER_SPRINT newbast1 @30101

    COPY_EXISTING ~SW1H39.ITM~ ~override~
      LPF ALTER_ITEM_EFFECT INT_VAR check_headers = 1 match_opcode = 12 parameter1 = 0 dicenumber = 1 dicesize = 6 END

      READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldbast1%~ ~%newbast1%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
END

///////////////////////////////////////////////////////////////////////////
// Purifier +4                                                           //
// Remove +4 extra damage vs. chaotic evil                               //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~SW1H64.ITM~ BEGIN
COPY ~forgotten-armament/eff/update_item/MO1H64.EFF~ ~override~
COPY ~forgotten-armament/spl/update_item/MO1H64.SPL~ ~override~
OUTER_SPRINT oldbast2 @30102
OUTER_SPRINT newbast2 @30103
OUTER_SPRINT oldbast5 @30108
OUTER_SPRINT newbast5 @30109
    
    COPY_EXISTING ~SW1H64.ITM~ ~override~
      LPF DELETE_EFFECT INT_VAR header_type = 1 match_opcode = 177 END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 177 target = 1 parameter1 = 0 parameter2 = 2 timing = 2 resist_dispel = 0 probability1 = 100 STR_VAR resource = ~MO1H64~ END

      READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldbast2%~ ~%newbast2%~
              REPLACE_TEXTUALLY ~%oldbast5%~ ~%newbast5%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
END

///////////////////////////////////////////////////////////////////////////
// Purifier +5                                                           //
// +20% Magic Resistance (previously +30%)                               //
// Remove +5 extra damage vs. chaotic evil, Dispel Magic, and Mass Cure  //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~SW1H65.ITM~ BEGIN
COPY ~forgotten-armament/eff/update_item/MO1H65.EFF~ ~override~
COPY ~forgotten-armament/spl/update_item/MO1H65.SPL~ ~override~
OUTER_SPRINT oldbast3 @30104
OUTER_SPRINT newbast3 @30105
OUTER_SPRINT oldbast4 @30106
OUTER_SPRINT newbast4 @30107
OUTER_SPRINT oldbast6 @30110
OUTER_SPRINT newbast6 @30111

    COPY_EXISTING ~SW1H65.ITM~ ~override~
      LPF ALTER_ITEM_EFFECT INT_VAR check_globals = 1 match_opcode = 166 parameter1 = 20 END
      LPF DELETE_ITEM_HEADER INT_VAR header_type = 3 END
      LPF DELETE_EFFECT INT_VAR header_type = 1 match_opcode = 177 END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 177 target = 1 parameter1 = 0 parameter2 = 2 timing = 2 resist_dispel = 0 probability1 = 100 STR_VAR resource = ~MO1H65~ END

      READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldbast3%~ ~%newbast3%~
              REPLACE_TEXTUALLY ~%oldbast4%~ ~%newbast4%~
              REPLACE_TEXTUALLY ~%oldbast6%~ ~%newbast6%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
END

///////////////////////////////////////////////////////////////////////////
// Purifier +5                                                           //
//                                                                       //
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Kondar                                                                //
//                                                                       //
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Club                                                                  //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Bone Club vs. Undead                                                  //
// +5 enchantment vs Undead (previously +3) w/ +10 extra damage to Undead//
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~BLUN23.ITM~ BEGIN
COPY ~forgotten-armament/eff/update_item/MOBL231.EFF~ ~override~
COPY ~forgotten-armament/eff/update_item/MOBL232.EFF~ ~override~
OUTER_SPRINT oldclub1 @30200
OUTER_SPRINT newclub1 @30201
OUTER_SPRINT oldclub2 @30202
OUTER_SPRINT newclub2 @30203

    COPY_EXISTING ~BLUN23.ITM~ ~override~
      LPF ALTER_ITEM_EFFECT INT_VAR check_globals = 1 match_opcode = 344 special = 5 END
      LPF ALTER_ITEM_EFFECT INT_VAR check_globals = 1 match_opcode = 177 STR_VAR resource = ~mobln232~ END
      LPF ALTER_ITEM_EFFECT INT_VAR check_headers = 1 match_opcode = 177 STR_VAR resource = ~mobln231~ END

      READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldclub1%~ ~%newclub1%~
              REPLACE_TEXTUALLY ~%oldclub2%~ ~%newclub2%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END

      READ_LONG 0xc desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0xc desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldclub2%~ ~%newclub2%~
            END
            SAY_EVALUATED 0xc ~%desc%~
          END
END

///////////////////////////////////////////////////////////////////////////
// Club of Detonation +3                                                 //
// +20% Fire Resistance                                                  //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~BLUN26.ITM~ BEGIN
OUTER_SPRINT oldclub3 @30204
OUTER_SPRINT newclub3 @30205
    
    COPY_EXISTING ~BLUN26.ITM~ ~override~
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 30 target = 1 parameter1 = 20 parameter2 = 0 timing = 2 resist_dispel = 0 probability1 = 100 END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 142 target = 1 parameter2 = 16 timing = 2 resist_dispel = 0 probability1 = 100 END

      READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldclub3%~ ~%newclub3%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END 
END

///////////////////////////////////////////////////////////////////////////
// Club of Detonation +5                                                 //
// +50% Fire Resistance, 10% chance per hit for fireball (previously 5%) //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~BLUN27.ITM~ BEGIN
OUTER_SPRINT oldclub4 @30206
OUTER_SPRINT newclub4 @30207
OUTER_SPRINT oldclub5 @30208
OUTER_SPRINT newclub5 @30209
    
    COPY_EXISTING ~BLUN27.ITM~ ~override~
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 30 target = 1 parameter1 = 50 parameter2 = 0 timing = 2 resist_dispel = 0 probability1 = 100 END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 142 target = 1 parameter2 = 16 timing = 2 resist_dispel = 0 probability1 = 100 END
      LPF ALTER_ITEM_EFFECT INT_VAR check_headers = 1 match_opcode = 146 probability2 = 90 END
      //LPF ALTER_ITEM_EFFECT INT_VAR check_headers = 1 match_opcode = 12 match_probability1 = 30 probability1 = 29 END

      READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldclub4%~ ~%newclub4%~
              REPLACE_TEXTUALLY ~%oldclub5%~ ~%newclub5%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END 
END

///////////////////////////////////////////////////////////////////////////
// Blackblood +3                                                         //
// +1d6 acid damage (previously +3)                                      //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~BLUN22.ITM~ BEGIN
OUTER_SPRINT oldclub6 @30210
OUTER_SPRINT newclub6 @30211
    
    COPY_EXISTING ~BLUN22.ITM~ ~override~
      LPF ALTER_ITEM_EFFECT INT_VAR check_headers = 1 match_opcode = 12 parameter1 = 0 dicenumber = 1 dicesize = 6 END

      READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldclub6%~ ~%newclub6%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END 
END

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Dagger                                                                //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Dagger of <CHARNAME>                                                  //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~DAGG19.ITM~ BEGIN
OUTER_SPRINT olddagger1 @30300
OUTER_SPRINT newdagger1 @30301
OUTER_SPRINT olddagger2 @30302
OUTER_SPRINT newdagger2 @30303

    COPY_EXISTING ~DAGG19.ITM~ ~override~
        WRITE_LONG 0x60 2
        LPF ALTER_ITEM_HEADER INT_VAR header_type=1 thac0_bonus = 2 damage_bonus = 2 END
        LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 142 target = 1 parameter2 = 63 timing = 2 resist_dispel = 2 probability1 = 100 END 
        LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 166 target = 1 parameter1 = 10 parameter2 = 0 timing = 2 resist_dispel = 0 probability1 = 100 END 
        LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 42 target = 1 parameter1 = 10 parameter2 = 2 timing = 2 resist_dispel = 0 probability1 = 100 END
        LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 42 target = 1 parameter1 = 10 parameter2 = 1 timing = 2 resist_dispel = 0 probability1 = 100 END
        LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 42 target = 1 parameter1 = 10 parameter2 = 0 timing = 2 resist_dispel = 0 probability1 = 100 END 

        READ_LONG 0x50 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x50 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%olddagger1%~ ~%newdagger1%~
              REPLACE_TEXTUALLY ~%olddagger2%~ ~%newdagger2%~
            END
            SAY_EVALUATED 0x50 ~%desc%~
          END
END

///////////////////////////////////////////////////////////////////////////
// Ice Talon +2                                                          //
// +1d4 cold damage (previously +1)                                      //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~MODAG02.ITM~ BEGIN
OUTER_SPRINT olddagger3 @30304
OUTER_SPRINT newdagger3 @30305

    COPY_EXISTING ~MODAG02.ITM~ ~override~
      LPF ALTER_ITEM_EFFECT INT_VAR check_headers = 1 match_opcode = 12 parameter1 = 0 dicenumber = 1 dicesize = 4 END

      READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%olddagger3%~ ~%newdagger3%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
END

///////////////////////////////////////////////////////////////////////////
// Acid-Etched Dagger +2                                                 //
// +1d4 acid damage (previously +1)                                      //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~BDDAGG05.ITM~ BEGIN
OUTER_SPRINT olddagger4 @30306
OUTER_SPRINT newdagger4 @30307

    COPY_EXISTING ~BDDAGG05.ITM~ ~override~
      LPF ALTER_ITEM_EFFECT INT_VAR check_headers = 1 match_opcode = 12 parameter1 = 0 dicenumber = 1 dicesize = 4 END

      READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%olddagger4%~ ~%newdagger4%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
END

///////////////////////////////////////////////////////////////////////////
// Dagger of Troll-fighting +1                                           //
// +1 fire damage (previously +1d4)                                      //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~BDDAGG02.ITM~ BEGIN
OUTER_SPRINT olddagger5 @30308
OUTER_SPRINT newdagger5 @30309

    COPY_EXISTING ~BDDAGG02.ITM~ ~override~
      LPF ALTER_ITEM_EFFECT INT_VAR check_headers = 1 match_opcode = 12 parameter1 = 1 dicenumber = 0 dicesize = 0 END

      READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%olddagger5%~ ~%newdagger5%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
END

///////////////////////////////////////////////////////////////////////////
// Boneblade +4                                                          //
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Heart of the Golem +2                                                 //
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// The Grave Binder +2                                                   //
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Flails                                                                //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Flail of Ages +5                                                      //
// Remove Magic Resistance and Free Action                               //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~BLUN30.ITM~ BEGIN
OUTER_SPRINT oldflail01 @30400

    COPY_EXISTING ~BLUN30.ITM~ ~override~
        LPF DELETE_ITEM_EQEFFECT INT_VAR opcode_to_delete = 46 END
        LPF DELETE_ITEM_EQEFFECT INT_VAR opcode_to_delete = 267 END
        LPF DELETE_ITEM_EQEFFECT INT_VAR opcode_to_delete = 142 END
        LPF DELETE_ITEM_EQEFFECT INT_VAR opcode_to_delete = 163 END
        LPF DELETE_ITEM_EQEFFECT INT_VAR opcode_to_delete = 101 END
        LPF DELETE_ITEM_EQEFFECT INT_VAR opcode_to_delete = 296 END
        LPF DELETE_ITEM_EQEFFECT INT_VAR opcode_to_delete = 166 END
        LPF DELETE_ITEM_EQEFFECT INT_VAR opcode_to_delete = 126 END
        LPF DELETE_ITEM_EQEFFECT INT_VAR opcode_to_delete = 169 END
        LPF DELETE_ITEM_EQEFFECT INT_VAR opcode_to_delete = 206 END
        LPF DELETE_ITEM_EQEFFECT INT_VAR opcode_to_delete = 162 END
        LPF DELETE_ITEM_EQEFFECT INT_VAR opcode_to_delete = 240 END

        READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldflail01%~ ~~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
END

///////////////////////////////////////////////////////////////////////////
// The Thresher +2                                                       //
// Physical Damage Resistance +10%                                       //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~BLUN39.ITM~ BEGIN
OUTER_SPRINT oldflail2 @30401
OUTER_SPRINT newflail2 @30402

    COPY_EXISTING ~BLUN39.ITM~ ~override~
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 86 target = 1 parameter1 = 10 parameter2 = 0 timing = 2 resist_dispel = 2 probability1 = 100 END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 87 target = 1 parameter1 = 10 parameter2 = 0 timing = 2 resist_dispel = 2 probability1 = 100 END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 88 target = 1 parameter1 = 10 parameter2 = 0 timing = 2 resist_dispel = 2 probability1 = 100 END

      READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldflail2%~ ~%newflail2%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
END

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Halberd                                                               //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Suryris Blade                                                         //
// 25% chance of kocking down an opponent                                //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~HALB03.ITM~ BEGIN
OUTER_SPRINT oldhalb1 @30500
OUTER_SPRINT newhalb1 @30501

    COPY_EXISTING ~HALB03.ITM~ ~override~
        LPF ADD_ITEM_EFFECT INT_VAR type = 1 opcode = 39 target = 2 parameter2 = 1 timing = 0 resist_dispel = 2 duration = 3 probability1 = 24 savingthrow = 4 special = 14 END

        READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldhalb1%~ ~%newhalb1%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
END

///////////////////////////////////////////////////////////////////////////
// Dragon's Breath +4                                                    //
// 1d10 +4 damage (previously just 1d10)                                 //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~HALB05.ITM~ BEGIN
OUTER_SPRINT oldhalb2 @30502
OUTER_SPRINT newhalb2 @30503

    COPY_EXISTING ~HALB05.ITM~ ~override~
        LPF ALTER_ITEM_HEADER INT_VAR header_type=1 damage_bonus = 4 END

        READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldhalb2%~ ~%newhalb2%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
END

///////////////////////////////////////////////////////////////////////////
// Duskblade                                                             //
// +3 item (previously +2), +1d6 cold damage (previously +2)             //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~HALB08.ITM~ BEGIN
OUTER_SPRINT oldhalb3 @30504
OUTER_SPRINT newhalb3 @30505
OUTER_SPRINT oldhalb4 @30506
OUTER_SPRINT newhalb4 @30507

    COPY_EXISTING ~HALB08.ITM~ ~override~
      WRITE_LONG 0x60 3
      LPF ALTER_ITEM_HEADER INT_VAR header_type=1 thac0_bonus = 3 damage_bonus = 3 END
      LPF ALTER_ITEM_EFFECT INT_VAR match_opcode = 12 check_headers = 1 parameter1 = 0 dicenumber = 1 dicesize = 6 END

        PATCH_FOR_EACH offset IN 0xc 0x54 BEGIN
        READ_LONG ~%offset%~ desc_strref
            PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
              READ_STRREF ~%offset%~ desc
              INNER_PATCH_SAVE desc ~%desc%~ BEGIN
                REPLACE_TEXTUALLY ~%oldhalb3%~ ~%newhalb3%~
                REPLACE_TEXTUALLY ~%oldhalb4%~ ~%newhalb4%~
              END
              SAY_EVALUATED ~%offset%~ ~%desc%~
            END
      END
END

///////////////////////////////////////////////////////////////////////////
// The Wave +4                                                           //
// 50% chance of draining (previously 15%)                               //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~HALB09.ITM~ BEGIN
OUTER_SPRINT oldhalb5 @30508
OUTER_SPRINT newhalb5 @30509

    COPY_EXISTING ~HALB09.ITM~ ~override~
        LPF ALTER_ITEM_EFFECT INT_VAR match_opcode = 12 check_headers = 1 probability1 = 49 END

        READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldhalb5%~ ~%newhalb5%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
END

///////////////////////////////////////////////////////////////////////////
// Cold Fury +2                                                          //
// +1d4 cold damage (previously +1d2)                                    //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~BDHALB03.ITM~ BEGIN
OUTER_SPRINT oldhalb6 @30510
OUTER_SPRINT newhalb6 @30511

    COPY_EXISTING ~BDHALB03.ITM~ ~override~
      LPF ALTER_ITEM_EFFECT INT_VAR match_opcode = 12 check_headers = 1 parameter1 = 0 dicenumber = 1 dicesize = 4 END

        PATCH_FOR_EACH offset IN 0xc 0x54 BEGIN
        READ_LONG ~%offset%~ desc_strref
            PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
              READ_STRREF ~%offset%~ desc
              INNER_PATCH_SAVE desc ~%desc%~ BEGIN
                REPLACE_TEXTUALLY ~%oldhalb6%~ ~%newhalb6%~
              END
              SAY_EVALUATED ~%offset%~ ~%desc%~
            END
      END
END

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Katana                                                                //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Crimson Dawn                                                          //
// +3 item                                                               //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~BDSW1H01.ITM~ BEGIN
OUTER_SPRINT oldkata4 @30606
OUTER_SPRINT newkata4 @30607

    COPY_EXISTING ~BDSW1H01.ITM~ ~override~
      WRITE_LONG 0x60 3
      LPF ALTER_ITEM_HEADER INT_VAR header_type=1 thac0_bonus = 3 damage_bonus = 3 END

      PATCH_FOR_EACH offset IN 0xc 0x54 BEGIN
        READ_LONG ~%offset%~ desc_strref
            PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
              READ_STRREF ~%offset%~ desc
              INNER_PATCH_SAVE desc ~%desc%~ BEGIN
                REPLACE_TEXTUALLY ~%oldkata4%~ ~%newkata4%~
              END
              SAY_EVALUATED ~%offset%~ ~%desc%~
            END
      END
END

///////////////////////////////////////////////////////////////////////////
// Hindo's Doom +3                                                       //
// 2d10+6 vs undead                                                      //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~SW1H70.ITM~ BEGIN
COPY ~forgotten-armament/eff/update_item/MO1H70.EFF~ ~override~
OUTER_SPRINT oldkata1 @30600
OUTER_SPRINT newkata1 @30601
    
    COPY_EXISTING ~SW1H70.ITM~ ~override~
        LPF ADD_ITEM_EFFECT INT_VAR opcode = 177 type = 1 target = 2 parameter1 = 4 parameter2 = 3 timing = 1 resist_dispel = 0 probability1 = 100 STR_VAR resource = ~mo1h70~ END

        READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldkata1%~ ~%newkata1%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
END

///////////////////////////////////////////////////////////////////////////
// Hindo's Doom +4                                                       //
// 2d10+8 vs undead, save vs -4 or be destroyed                          //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~SW1H71.ITM~ BEGIN
COPY ~forgotten-armament/eff/update_item/MO1H71.EFF~ ~override~
OUTER_SPRINT oldkata2 @30602
OUTER_SPRINT newkata2 @30603
OUTER_SPRINT oldkata3 @30604
OUTER_SPRINT newkata3 @30605
    
    COPY_EXISTING ~SW1H71.ITM~ ~override~
        LPF ADD_ITEM_EFFECT INT_VAR opcode = 177 type = 1 target = 2 parameter1 = 4 parameter2 = 3 timing = 1 resist_dispel = 0 probability1 = 100 STR_VAR resource = ~mesdie~ END
        LPF ADD_ITEM_EFFECT INT_VAR opcode = 177 type = 1 target = 2 parameter1 = 4 parameter2 = 3 timing = 1 resist_dispel = 0 probability1 = 100 STR_VAR resource = ~die~ END
        LPF ADD_ITEM_EFFECT INT_VAR opcode = 177 type = 1 target = 2 parameter1 = 4 parameter2 = 3 timing = 1 resist_dispel = 0 probability1 = 100 STR_VAR resource = ~mo1h71~ END

        READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldkata2%~ ~%newkata2%~
              REPLACE_TEXTUALLY ~%oldkata3%~ ~%newkata3%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
END

///////////////////////////////////////////////////////////////////////////
// Master Li's Way +2                                                    //
// +1d4 acid damage (previously +1)                                      //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~MO1H55.ITM~ BEGIN
OUTER_SPRINT oldkata5 @30608
OUTER_SPRINT newkata5 @30609

    COPY_EXISTING ~MO1H55.ITM~ ~override~
      LPF ALTER_ITEM_EFFECT INT_VAR match_opcode = 12 check_headers = 1 parameter1 = 0 dicenumber = 1 dicesize = 4 END

        PATCH_FOR_EACH offset IN 0xc 0x54 BEGIN
        READ_LONG ~%offset%~ desc_strref
            PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
              READ_STRREF ~%offset%~ desc
              INNER_PATCH_SAVE desc ~%desc%~ BEGIN
                REPLACE_TEXTUALLY ~%oldkata5%~ ~%newkata5%~
              END
              SAY_EVALUATED ~%offset%~ ~%desc%~
            END
      END
END

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Long Sword                                                            //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Blackrazor                                                            //
// +4 weapon                                                             //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~MISCBC.ITM~ BEGIN

    COPY_EXISTING ~MISCBC.ITM~ ~override\MOBLK01.ITM~
      WRITE_LONG 0x60 4
      LPF ALTER_ITEM_HEADER INT_VAR header_type=1 thac0_bonus = 4 damage_bonus = 4 END
      LPF ALTER_ITEM_EFFECT INT_VAR match_opcode = ~-1~ check_headers = 1 probability1 = 24 END
      SAY NAME1 @30700
      SAY NAME2 @30700
      SAY DESC  @30701
END

///////////////////////////////////////////////////////////////////////////
// Daystar                                                               //
// +3 weapon                                                             //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~SW1H31.ITM~ BEGIN
OUTER_SPRINT oldlong2 @30702
OUTER_SPRINT newlong2 @30703

    COPY_EXISTING ~SW1H31.ITM~ ~override~
      WRITE_LONG 0x60 3
      LPF ALTER_ITEM_HEADER INT_VAR header_type=1 thac0_bonus = 3 damage_bonus = 3 END

      PATCH_FOR_EACH offset IN 0xc 0x54 BEGIN
        READ_LONG ~%offset%~ desc_strref
            PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
              READ_STRREF ~%offset%~ desc
              INNER_PATCH_SAVE desc ~%desc%~ BEGIN
                REPLACE_TEXTUALLY ~%oldlong2%~ ~%newlong2%~
              END
              SAY_EVALUATED ~%offset%~ ~%desc%~
            END
      END
END

///////////////////////////////////////////////////////////////////////////
// Angurvadal +5                                                         //
// 2d4+1 fire damage (previously 1d4+1)                                  //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~SW1H61.ITM~ BEGIN
OUTER_SPRINT oldlong3 @30704
OUTER_SPRINT newlong3 @30705

    COPY_EXISTING ~SW1H61.ITM~ ~override~
      LPF ALTER_ITEM_EFFECT INT_VAR match_opcode = 12 check_headers = 1 dicenumber = 2 END

      READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldlong3%~ ~%newlong3%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
END

///////////////////////////////////////////////////////////////////////////
// Angurvadal +4                                                         //
// +1d8 fire damage (previously +1)                                      //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~SW1H60.ITM~ BEGIN
OUTER_SPRINT oldlong4 @30706
OUTER_SPRINT newlong4 @30707

    COPY_EXISTING ~SW1H60.ITM~ ~override~
      LPF ALTER_ITEM_EFFECT INT_VAR check_headers = 1 match_opcode = 12 parameter1 = 0 dicenumber = 1 dicesize = 8 END

      READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldlong4%~ ~%newlong4%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
END

///////////////////////////////////////////////////////////////////////////
// Varscona +2                                                           //
// +1d4 cold damage (previously +1)                                      //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~SW1H06.ITM~ BEGIN
OUTER_SPRINT oldlong5 @30708
OUTER_SPRINT newlong5 @30709

    COPY_EXISTING ~SW1H06.ITM~ ~override~
      LPF ALTER_ITEM_EFFECT INT_VAR check_headers = 1 match_opcode = 12 parameter1 = 0 dicenumber = 1 dicesize = 4 END

      READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldlong5%~ ~%newlong5%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
END

///////////////////////////////////////////////////////////////////////////
// Tongue of Acid +3                                                     //
// +1d6 acid damage (previously +1d3)                                    //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~BDSW1H02.ITM~ BEGIN
OUTER_SPRINT oldlong6 @30710
OUTER_SPRINT newlong6 @30711

    COPY_EXISTING ~BDSW1H02.ITM~ ~override~
      LPF ALTER_ITEM_EFFECT INT_VAR match_opcode = 12 check_headers = 1 parameter1 = 0 dicenumber = 1 dicesize = 6 END

        PATCH_FOR_EACH offset IN 0xc 0x54 BEGIN
        READ_LONG ~%offset%~ desc_strref
            PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
              READ_STRREF ~%offset%~ desc
              INNER_PATCH_SAVE desc ~%desc%~ BEGIN
                REPLACE_TEXTUALLY ~%oldlong6%~ ~%newlong6%~
              END
              SAY_EVALUATED ~%offset%~ ~%desc%~
            END
      END
END

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Mace                                                                  //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Ardulia's Fall                                                        //
// Better save vs hit, +3 weapon, +2 wisdom                              //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~BLUN20.ITM~ BEGIN
OUTER_SPRINT oldmace1 @30800
OUTER_SPRINT newmace1 @30801
OUTER_SPRINT oldmace2 @30802
OUTER_SPRINT newmace2 @30803
OUTER_SPRINT oldmace3 @30804
OUTER_SPRINT newmace3 @30805
OUTER_SPRINT oldmace5 @30808
OUTER_SPRINT newmace5 @30809

    COPY_EXISTING ~BLUN20.ITM~ ~override~
      WRITE_LONG 0x60 3
      LPF ALTER_ITEM_HEADER INT_VAR header_type=1 thac0_bonus = 3 damage_bonus = 3 END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 49 target = 1 parameter1 = 2 parameter2 = 0 timing = 2 resist_dispel = 2 probability1 = 100 END
      LPF ALTER_ITEM_EFFECT INT_VAR match_opcode = 0 check_headers = 1 savebonus = ~-2~ END
      LPF ALTER_ITEM_EFFECT INT_VAR match_opcode = 54 check_headers = 1 savebonus = ~-2~ END
      LPF ALTER_ITEM_EFFECT INT_VAR match_opcode = 142 check_headers = 1 savebonus = ~-2~ END
      LPF ALTER_ITEM_EFFECT INT_VAR match_opcode = 139 check_headers = 1 savebonus = ~-2~ END
      LPF ALTER_ITEM_EFFECT INT_VAR match_opcode = 141 check_headers = 1 savebonus = ~-2~ END
      LPF ALTER_ITEM_EFFECT INT_VAR match_opcode = 174 check_headers = 1 savebonus = ~-2~ END
      LPF ALTER_ITEM_EFFECT INT_VAR match_opcode = 40 check_headers = 1 savebonus = ~-2~ END

      PATCH_FOR_EACH offset IN 0xc 0x54 BEGIN
        READ_LONG ~%offset%~ desc_strref
            PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
              READ_STRREF ~%offset%~ desc
              INNER_PATCH_SAVE desc ~%desc%~ BEGIN
                REPLACE_TEXTUALLY ~%oldmace5%~ ~%newmace5%~
                REPLACE_TEXTUALLY ~%oldmace1%~ ~%newmace1%~
                REPLACE_TEXTUALLY ~%oldmace2%~ ~%newmace2%~
                REPLACE_TEXTUALLY ~%oldmace3%~ ~%newmace3%~
              END
              SAY_EVALUATED ~%offset%~ ~%desc%~
            END
      END
END

///////////////////////////////////////////////////////////////////////////
// Krotan's Skullcrusher                                                 //
// +5% crit strike for this weapon                                       //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~BLUN11.ITM~ BEGIN
OUTER_SPRINT oldmace4 @30806
OUTER_SPRINT newmace4 @30807

    COPY_EXISTING ~BLUN11.ITM~ ~override~
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 301 target = 1 parameter1 = 1 parameter2 = 1 timing = 2 resist_dispel = 0 probability1 = 100 END

      READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldmace4%~ ~%newmace4%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
END

///////////////////////////////////////////////////////////////////////////
// Storm Star +5                                                         //
// +2d4+1 electrical damage                                              //
// 10% chance of chain lightning                                         //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~BLUN29.ITM~ BEGIN
OUTER_SPRINT oldmace6 @30810
OUTER_SPRINT newmace6 @30811
OUTER_SPRINT oldmace7 @30812
OUTER_SPRINT newmace7 @30813

    COPY_EXISTING ~BLUN29.ITM~ ~override~
      LPF ALTER_ITEM_EFFECT INT_VAR match_opcode = 146 check_headers = 1 probability1 = 9 END
      LPF ALTER_ITEM_EFFECT INT_VAR check_headers = 1 match_opcode = 12 parameter1 = 1 dicenumber = 2 dicesize = 4 END

      READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldmace6%~ ~%newmace6%~
              REPLACE_TEXTUALLY ~%oldmace7%~ ~%newmace7%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
END

///////////////////////////////////////////////////////////////////////////
// Skullcrusher                                                          //
// +10% crit strike with this weapon                                     //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~BLUN18.ITM~ BEGIN
OUTER_SPRINT oldmace8 @30814
OUTER_SPRINT newmace8 @30815
    
    COPY_EXISTING ~BLUN18.ITM~ ~override~
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 301 target = 1 parameter1 = 2 parameter2 = 1 timing = 2 resist_dispel = 0 probability1 = 100 END

      READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldmace8%~ ~%newmace8%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
END

///////////////////////////////////////////////////////////////////////////
// Soldier's Might +2 & Petty's Tempest +2                               //
// +1d4 elemental damage (previously +1)                                 //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~MOBLN02.ITM~ AND FILE_EXISTS_IN_GAME ~MOBLN01.ITM~ BEGIN
OUTER_SPRINT oldmace9 @30816
OUTER_SPRINT newmace9 @30817
    
    ACTION_FOR_EACH blunt IN 1 2 BEGIN
      COPY_EXISTING ~MOBLN0%blunt%.ITM~ ~override~
        LPF ALTER_ITEM_EFFECT INT_VAR check_headers = 1 match_opcode = 12 parameter1 = 0 dicenumber = 1 dicesize = 4 END

        READ_LONG 0x54 desc_strref
            PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
              READ_STRREF 0x54 desc
              INNER_PATCH_SAVE desc ~%desc%~ BEGIN
                REPLACE_TEXTUALLY ~%oldmace9%~ ~%newmace9%~
              END
              SAY_EVALUATED 0x54 ~%desc%~
            END
    END

END

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Morning Star                                                          //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// The Sleeper +2                                                        //
// -2 bonus to save (previously +4 bonus)                                //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~BLUN16.ITM~ BEGIN
OUTER_SPRINT oldmorning1 @30900
OUTER_SPRINT newmorning1 @30901

    COPY_EXISTING ~BLUN16.ITM~ ~override~
      LPF ALTER_ITEM_EFFECT INT_VAR match_opcode = 177 check_headers = 1 savebonus = ~-2~ END

      READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldmorning1%~ ~%newmorning1%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
END

///////////////////////////////////////////////////////////////////////////
// Ice Star +4                                                           //
// +1d8 cold damage (previously +1d4)                                    //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~BLUN35.ITM~ BEGIN
OUTER_SPRINT oldmorning2 @30902
OUTER_SPRINT newmorning2 @30903

    COPY_EXISTING ~BLUN35.ITM~ ~override~
      LPF ALTER_ITEM_EFFECT INT_VAR check_headers = 1 match_opcode = 12 parameter1 = 0 dicenumber = 1 dicesize = 8 END

      READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldmorning2%~ ~%newmorning2%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
END

///////////////////////////////////////////////////////////////////////////
// Blazing Glory +3                                                      //
// +1d6 fire damage (previously +1)                                      //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~BDBLUN09.ITM~ BEGIN
OUTER_SPRINT oldmorning3 @30904
OUTER_SPRINT newmorning3 @30905

    COPY_EXISTING ~BDBLUN09.ITM~ ~override~
      LPF ALTER_ITEM_EFFECT INT_VAR match_opcode = 12 check_headers = 1 parameter1 = 0 dicenumber = 1 dicesize = 6 END

        PATCH_FOR_EACH offset IN 0xc 0x54 BEGIN
        READ_LONG ~%offset%~ desc_strref
            PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
              READ_STRREF ~%offset%~ desc
              INNER_PATCH_SAVE desc ~%desc%~ BEGIN
                REPLACE_TEXTUALLY ~%oldmorning3%~ ~%newmorning3%~
              END
              SAY_EVALUATED ~%offset%~ ~%desc%~
            END
      END
END

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Ninja-To                                                              //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Usuno's Blade +4                                                      //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~SW1H67.ITM~ BEGIN
OUTER_SPRINT oldninja1 @31000
OUTER_SPRINT newninja1 @31001

    COPY_EXISTING ~SW1H67.ITM~ ~override~
      LPF CLONE_EFFECT INT_VAR match_opcode = 12 opcode = 12 probability1 = 100 dicenumber = 1 dicesize = 8 savingthrow = 0 special = 0 END

      READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldninja1%~ ~%newninja1%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END

END

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Staff                                                                 //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Cleric's Staff +3                                                     //
// +2 Wisdom                                                             //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~STAF19.ITM~ BEGIN
OUTER_SPRINT oldstaff1 @31100
OUTER_SPRINT newstaff1 @31101

    COPY_EXISTING ~STAF19.ITM~ ~override~
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 49 target = 1 parameter1 = 2 parameter2 = 0 timing = 2 resist_dispel = 2 probability1 = 100 END

      READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldstaff1%~ ~%newstaff1%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
END

///////////////////////////////////////////////////////////////////////////
// Martial Staff +3                                                      //
// AC: +1 Bonus, Regenerate 1 Hit Point per round                        //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~STAF08.ITM~ BEGIN
OUTER_SPRINT oldstaff2 @31102
OUTER_SPRINT newstaff2 @31103

    COPY_EXISTING ~STAF08.ITM~ ~override~
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 142 target = 1 parameter2 = 87 timing = 2 resist_dispel = 0 probability1 = 100 END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 98 target = 1 parameter1 = 6 parameter2 = 3 timing = 2 resist_dispel = 0 probability1 = 100 END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 0 target = 1 parameter1 = 1 timing = 2 resist_dispel = 0 probability1 = 100 END

      READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldstaff2%~ ~%newstaff2%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
END

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Scimitar                                                              //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Rashad Talon                                                          //
// +1d6 Slashing on Crit                                                 //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~SW1H23.ITM~ BEGIN
COPY ~forgotten-armament/eff/update_item/MO1H23.EFF~ ~override~
OUTER_SPRINT oldscimi1 @31200
OUTER_SPRINT newscimi1 @31201

    COPY_EXISTING ~SW1H23.ITM~ ~override~
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 341 target = 1 parameter1 = 1 parameter2 = 1 timing = 2 resist_dispel = 0 probability1 = 100 STR_VAR resource = ~mo1h23~ END

      READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldscimi1%~ ~%newscimi1%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
END

///////////////////////////////////////////////////////////////////////////
// Spectral Brand +5                                                     //
// Replace Piercing Strike with Critical Strike                          //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~SW1H69.ITM~ BEGIN
OUTER_SPRINT oldscimi2 @31202
OUTER_SPRINT newscimi2 @31203
OUTER_SPRINT oldscimi3 @31204
OUTER_SPRINT newscimi3 @31205
OUTER_SPRINT oldscimi4 @31206
OUTER_SPRINT newscimi4 @31207
OUTER_SPRINT oldscimi6 @31210
OUTER_SPRINT newscimi6 @31211


    COPY_EXISTING ~SW1H69.ITM~ ~override~
      LPF ALTER_ITEM_EFFECT INT_VAR match_opcode = 142 check_headers = 1 parameter2 = 152 duration = 6 END
      LPF ALTER_ITEM_EFFECT INT_VAR match_opcode = 54 check_headers = 1 new_opcode = 301 parameter1 = 20 duration = 6 END
      LPF ALTER_ITEM_EFFECT INT_VAR match_opcode = 215 check_headers = 1 target = 2 STR_VAR resource = ~sppowatk~ END
      LPF CLONE_EFFECT INT_VAR match_opcode = 301 opcode = 282 parameter2 = 3 END
      LPF CLONE_EFFECT INT_VAR match_opcode = 142 opcode = 174 timing = 1 duration = 0 STR_VAR resource = ~eff_p82~ END
      LPF CLONE_EFFECT INT_VAR match_opcode = 142 opcode = 174 timing = 4 duration = 12 STR_VAR resource = ~eff_e01~ END
      LPF ALTER_ITEM_EFFECT INT_VAR check_headers = 1 match_opcode = 12 parameter1 = 1 dicenumber = 2 dicesize = 4 END

      READ_LONG 0x64 hf //Extended header offset
      READ_SHORT 0x68 hc //Extended header count
      FOR (i1 = 0; i1 < hc; i1 += 1) BEGIN //Cycle through headers
        READ_BYTE (0x38 * i1 + hf) pt //Attack type
        PATCH_IF pt = 3 BEGIN
          READ_ASCII (0x38 * i1 + hf + 4) icon
          PATCH_IF ("%icon%" STRING_EQUAL_CASE "SPPR313B") BEGIN
            WRITE_ASCII (0x38 * i1 + hf + 4) ~spcl905b~ #8
          END
        END
      END

      READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldscimi2%~ ~%newscimi2%~
              REPLACE_TEXTUALLY ~%oldscimi3%~ ~%newscimi3%~
              REPLACE_TEXTUALLY ~%oldscimi4%~ ~%newscimi4%~
              REPLACE_TEXTUALLY ~%oldscimi6%~ ~%newscimi6%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
    
    ACTION_GET_STRREF ~70621~ pierce_strike

    OUTER_PATCH_SAVE pierce_strike ~%pierce_strike%~ BEGIN
      REPLACE_TEXTUALLY ~%oldscimi2%~ ~%newscimi2%~
    END

    STRING_SET_EVALUATE ~70621~ ~%pierce_strike%~
END

///////////////////////////////////////////////////////////////////////////
// Water's Edge +3                                                       //
// +5% crit chance with this weapon                                      //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~SW1H52.ITM~ BEGIN
OUTER_SPRINT oldscimi5 @31208
OUTER_SPRINT newscimi5 @31209

    COPY_EXISTING ~SW1H52.ITM~ ~override~
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 301 target = 1 parameter1 = 1 parameter2 = 1 timing = 2 resist_dispel = 0 probability1 = 100 END

      READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldscimi5%~ ~%newscimi5%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
END

///////////////////////////////////////////////////////////////////////////
// Spectral Brand +4                                                     //
// +1d8 cold damage (previously 1d4)                                     //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~SW1H68.ITM~ BEGIN
OUTER_SPRINT oldscimi7 @31212
OUTER_SPRINT newscimi7 @31213

    COPY_EXISTING ~SW1H68.ITM~ ~override~
      LPF ALTER_ITEM_EFFECT INT_VAR check_headers = 1 match_opcode = 12 dicenumber = 1 dicesize = 8 END

      READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldscimi7%~ ~%newscimi7%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
END

///////////////////////////////////////////////////////////////////////////
// Laughing Blade +2                                                     //
// +1d4 cold damage (previously +1)                                      //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~MO1H30.ITM~ BEGIN
OUTER_SPRINT oldscimi8 @31214
OUTER_SPRINT newscimi8 @31215

    COPY_EXISTING ~MO1H30.ITM~ ~override~
      LPF ALTER_ITEM_EFFECT INT_VAR check_headers = 1 match_opcode = 12 parameter1 = 0 dicenumber = 1 dicesize = 4 END

      READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldscimi8%~ ~%newscimi8%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
END

///////////////////////////////////////////////////////////////////////////
// Dervish Crescent +2                                                   //
// +1d4 fire damage (previously +1)                                      //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~BDSW1H08.ITM~ BEGIN
OUTER_SPRINT oldscimi9 @31216
OUTER_SPRINT newscimi9 @31217

    COPY_EXISTING ~BDSW1H08.ITM~ ~override~
      LPF ALTER_ITEM_EFFECT INT_VAR match_opcode = 12 check_headers = 1 parameter1 = 0 dicenumber = 1 dicesize = 4 END

        PATCH_FOR_EACH offset IN 0xc 0x54 BEGIN
        READ_LONG ~%offset%~ desc_strref
            PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
              READ_STRREF ~%offset%~ desc
              INNER_PATCH_SAVE desc ~%desc%~ BEGIN
                REPLACE_TEXTUALLY ~%oldscimi9%~ ~%newscimi9%~
              END
              SAY_EVALUATED ~%offset%~ ~%desc%~
            END
      END
END

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Short Sword                                                           //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Cutthroat +4                                                          //
// Inflicts 2 points of bleeding damage per hit (one point per round)    //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~SW1H28.ITM~ BEGIN
OUTER_SPRINT oldshort1 @31300
OUTER_SPRINT newshort1 @31301

    COPY_EXISTING ~SW1H28.ITM~ ~override~
      LPF ADD_ITEM_EFFECT INT_VAR opcode = 146 type = 1 target = 2 parameter1 = 1 parameter2 = 1 timing = 1 resist_dispel = 0 probability1 = 100 STR_VAR resource = ~bdsw1h21~ END

      READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldshort1%~ ~%newshort1%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
END

///////////////////////////////////////////////////////////////////////////
// Short Sword of Mask                                                   //
// Non-Detection, Remove Level Drain, 5% chance of proccing assassination//
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~SW1H58.ITM~ AND FILE_EXISTS_IN_GAME ~SW1H59.ITM~ BEGIN
OUTER_SPRINT oldshort2 @31302
OUTER_SPRINT newshort2 @31303
OUTER_SPRINT oldshort3 @31304
OUTER_SPRINT newshort3 @31305

    COPY_EXISTING ~SW1H58.ITM~ ~override~
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 69 target = 1 timing = 2 resist_dispel = 0 probability1 = 100 END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 142 target = 1 parameter2 = 31 timing = 2 resist_dispel = 0 probability1 = 100 END

      READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldshort2%~ ~%newshort2%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END

    COPY_EXISTING ~SW1H59.ITM~ ~override~
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 69 target = 1 timing = 2 resist_dispel = 0 probability1 = 100 END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 142 target = 1 parameter2 = 31 timing = 2 resist_dispel = 0 probability1 = 100 END
      LPF DELETE_EFFECT INT_VAR header_type = 1 match_opcode = 139 END
      LPF DELETE_EFFECT INT_VAR header_type = 1 match_opcode = 216 END
      LPF DELETE_EFFECT INT_VAR header_type = 1 match_opcode = 141 END
      LPF ADD_ITEM_EFFECT INT_VAR opcode = 303 type = 1 target = 1 parameter2 = 1 timing = 0 resist_dispel = 2 duration = 6 probability1 = 100 probability2 = 95 END
      LPF ADD_ITEM_EFFECT INT_VAR opcode = 142 type = 1 target = 1 parameter2 = 156 timing = 0 resist_dispel = 2 duration = 6 probability1 = 100 probability2 = 95 END
      LPF ADD_ITEM_EFFECT INT_VAR opcode = 282 type = 1 target = 1 parameter1 = 4 parameter2 = 3 timing = 0 resist_dispel = 2 duration = 6 probability1 = 100 probability2 = 95 END
      LPF ADD_ITEM_EFFECT INT_VAR opcode = 174 type = 1 target = 1 timing = 4 resist_dispel = 2 duration = 6 probability1 = 100 probability2 = 95 STR_VAR resource = ~eff_e01~ END
      LPF ADD_ITEM_EFFECT INT_VAR opcode = 174 type = 1 target = 1 timing = 1 resist_dispel = 2 duration = 0 probability1 = 100 probability2 = 95 STR_VAR resource = ~wwattack~ END
      LPF ADD_ITEM_EFFECT INT_VAR opcode = 215 type = 1 target = 2 parameter2 = 0 timing = 1 resist_dispel = 0 duration = 0 probability1 = 100 probability2 = 95 STR_VAR resource = ~spgrwhrl~ END

      READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldshort2%~ ~%newshort2%~
              REPLACE_TEXTUALLY ~%oldshort3%~ ~%newshort3%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
END

///////////////////////////////////////////////////////////////////////////
// The Shadow's Blade +3                                                 //
// Luck +1, +1 Backstab (Thieves only)                                   //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~SW1H10.ITM~ BEGIN
COPY ~forgotten-armament/eff/update_item/MO1H10.EFF~ ~override~
OUTER_SPRINT oldshort4 @31306
OUTER_SPRINT newshort4 @31307

    COPY_EXISTING ~SW1H10.ITM~ ~override~
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 22 target = 1 parameter1 = 1 parameter2 = 0 timing = 2 resist_dispel = 0 probability1 = 100 END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 177 target = 1 parameter1 = 205 parameter2 = 5 timing = 2 resist_dispel = 0 probability1 = 100 STR_VAR resource = ~mo1h10~ END

      READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldshort4%~ ~%newshort4%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
END

///////////////////////////////////////////////////////////////////////////
// The Whistling Sword                                                   //
// Vocalize                                                              //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~SW1H09.ITM~ BEGIN
OUTER_SPRINT oldshort5 @31308
OUTER_SPRINT newshort5 @31309
OUTER_SET silenced = RESOLVE_STR_REF (@31310)
OUTER_SET silence = RESOLVE_STR_REF (@31311)

    COPY_EXISTING ~SW1H09.ITM~ ~override~
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 267 target = 1 parameter1 = ~%silenced%~ timing = 2 resist_dispel = 2 probability1 = 100 END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 267 target = 1 parameter1 = ~%silence%~ timing = 2 resist_dispel = 2 probability1 = 100 END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 142 target = 1 parameter2 = 103 timing = 2 resist_dispel = 2 probability1 = 100 END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 101 target = 1 parameter2 = 38 timing = 2 resist_dispel = 2 probability1 = 100 END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 169 target = 1 parameter2 = 34 timing = 2 resist_dispel = 2 probability1 = 100 END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 48 target = 1 timing = 1 resist_dispel = 2 probability1 = 100 END

      READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldshort5%~ ~%newshort5%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
END

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Spear                                                                 //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Heartwood Spear +4                                                    //
// +1d8 electrical damage (previously +1d4)                              //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~MOSP02.ITM~ BEGIN
OUTER_SPRINT oldspear1 @31400
OUTER_SPRINT newspear1 @31401

    COPY_EXISTING ~MOSP02.ITM~ ~override~
      LPF ALTER_ITEM_EFFECT INT_VAR check_headers = 1 match_opcode = 12 parameter1 = 0 dicenumber = 1 dicesize = 8 END

      READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldspear1%~ ~%newspear1%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
END

///////////////////////////////////////////////////////////////////////////
// Ixil's Spike +6                                                       //
// Remove Free Action, Save vs. Paralysis at -4 negates                  //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~SPER12.ITM~ BEGIN
OUTER_SPRINT oldspear2 @31402
OUTER_SPRINT oldspear3 @31403
OUTER_SPRINT newspear3 @31404


    COPY_EXISTING ~SPER12.ITM~ ~override~
        LPF DELETE_ITEM_EQEFFECT INT_VAR opcode_to_delete = 46 END
        LPF DELETE_ITEM_EQEFFECT INT_VAR opcode_to_delete = 267 END
        LPF DELETE_ITEM_EQEFFECT INT_VAR opcode_to_delete = 142 END      
        LPF DELETE_ITEM_EQEFFECT INT_VAR opcode_to_delete = 163 END
        LPF DELETE_ITEM_EQEFFECT INT_VAR opcode_to_delete = 101 END
        LPF DELETE_ITEM_EQEFFECT INT_VAR opcode_to_delete = 296 END
        LPF DELETE_ITEM_EQEFFECT INT_VAR opcode_to_delete = 126 END
        LPF DELETE_ITEM_EQEFFECT INT_VAR opcode_to_delete = 169 END
        LPF DELETE_ITEM_EQEFFECT INT_VAR opcode_to_delete = 206 END
        LPF DELETE_ITEM_EQEFFECT INT_VAR opcode_to_delete = 162 END
        LPF DELETE_ITEM_EQEFFECT INT_VAR opcode_to_delete = 240 END
        LPF ALTER_ITEM_EFFECT INT_VAR check_headers = 1 match_opcode = 12 savebonus = ~-4~ END
        LPF ALTER_ITEM_EFFECT INT_VAR check_headers = 1 match_opcode = 39 savebonus = ~-4~ END

        READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldspear2%~ ~~
              REPLACE_TEXTUALLY ~%oldspear3%~ ~%newspear3%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
END

///////////////////////////////////////////////////////////////////////////
// Spear of Kuldahar +3                                                  //
// Physical Damage Resistance +20%                                       //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~WASPEAR.ITM~ BEGIN
OUTER_SPRINT oldspear4 @31405
OUTER_SPRINT newspear4 @31406

    COPY_EXISTING ~WASPEAR.ITM~ ~override~
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 86 target = 1 parameter1 = 20 parameter2 = 0 timing = 2 resist_dispel = 2 probability1 = 100 END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 87 target = 1 parameter1 = 20 parameter2 = 0 timing = 2 resist_dispel = 2 probability1 = 100 END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 88 target = 1 parameter1 = 20 parameter2 = 0 timing = 2 resist_dispel = 2 probability1 = 100 END

      READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldspear4%~ ~%newspear4%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
END

///////////////////////////////////////////////////////////////////////////
// Spear of Withering +4                                                 //
// +1d8 poison damage (previously +4)                                    //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~SPER10.ITM~ BEGIN
OUTER_SPRINT oldspear5 @31407
OUTER_SPRINT newspear5 @31408

    COPY_EXISTING ~SPER10.ITM~ ~override~
      LPF ALTER_ITEM_EFFECT INT_VAR check_headers = 1 match_opcode = 12 parameter1 = 0 dicenumber = 1 dicesize = 8 END

      READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldspear5%~ ~%newspear5%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END     
END

///////////////////////////////////////////////////////////////////////////
// Briarspike +2                                                         //
// +1d4 poison damage (previously +2)                                    //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~MOSP01.ITM~ BEGIN
OUTER_SPRINT oldspear6 @31409
OUTER_SPRINT newspear6 @31410

    COPY_EXISTING ~MOSP01.ITM~ ~override~
      LPF ALTER_ITEM_EFFECT INT_VAR match_opcode = 12 check_headers = 1 parameter1 = 0 dicenumber = 1 dicesize = 4 END

        PATCH_FOR_EACH offset IN 0xc 0x54 BEGIN
        READ_LONG ~%offset%~ desc_strref
            PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
              READ_STRREF ~%offset%~ desc
              INNER_PATCH_SAVE desc ~%desc%~ BEGIN
                REPLACE_TEXTUALLY ~%oldspear6%~ ~%newspear6%~
              END
              SAY_EVALUATED ~%offset%~ ~%desc%~
            END
      END
END

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Two-Handed Sword                                                      //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Carsomyr +5                                                           //
// +10% Magic Resistance (previously set to 50%)                         //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~SW2H10.ITM~ BEGIN
OUTER_SPRINT oldtwohand1 @31500
OUTER_SPRINT newtwohand1 @31501

    COPY_EXISTING ~SW2H10.ITM~ ~override~ 
      LPF ALTER_ITEM_EFFECT INT_VAR check_globals = 1 match_opcode = 166 parameter1 = 10 parameter2 = 0 END

      READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldtwohand1%~ ~%newtwohand1%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
END

///////////////////////////////////////////////////////////////////////////
// Carsomyr +6                                                           //
// +25% Magic Resistance (previously set to 50%)                         //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~SW2H19.ITM~ BEGIN
OUTER_SPRINT oldtwohand7 @31500
OUTER_SPRINT newtwohand7 @31514

    COPY_EXISTING ~SW2H19.ITM~ ~override~ 
      LPF ALTER_ITEM_EFFECT INT_VAR check_globals = 1 match_opcode = 166 parameter1 = 25 parameter2 = 0 END

      READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldtwohand7%~ ~%newtwohand7%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
END

///////////////////////////////////////////////////////////////////////////
// Ir'revrykal                                                           //
// Remove Dispel on Hit and Immunity to Charm                            //
// Add vorpal strike and healing per hit                                 //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~OHREAVER.ITM~ BEGIN
OUTER_SPRINT oldtwohand2 @31502
OUTER_SPRINT newtwohand2 @31503

    COPY_EXISTING ~OHREAVER.ITM~ ~override~
      LPF DELETE_EFFECT INT_VAR header_type = 1 match_opcode = 81 END
      LPF DELETE_EFFECT INT_VAR header_type = 1 match_opcode = 77 END
      LPF DELETE_EFFECT INT_VAR header_type = 1 match_opcode = 58 END
      LPF DELETE_EFFECT INT_VAR header_type = 1 match_opcode = 139 END
      LPF DELETE_EFFECT INT_VAR header_type = 1 match_opcode = 215 END
      LPF DELETE_EFFECT INT_VAR header_type = 1 match_opcode = 240 END
      LPF DELETE_EFFECT INT_VAR header_type = 1 match_opcode = 177 END
      LPF DELETE_EFFECT INT_VAR header_type = 1 match_opcode = 267 END
      LPF DELETE_EFFECT INT_VAR header_type = 1 match_opcode = 101 END
      LPF DELETE_EFFECT INT_VAR header_type = 1 match_opcode = 142 END
      LPF DELETE_EFFECT INT_VAR header_type = 1 match_opcode = 296 END
      LPF DELETE_EFFECT INT_VAR header_type = 1 match_opcode = 169 END
      LPF ADD_ITEM_EFFECT INT_VAR opcode = 12 type = 1 target = 2 parameter1 = 5 parameter2 = 4194304 timing = 1 resist_dispel = 0 probability1 = 100 special = 1 END
      LPF ADD_ITEM_EFFECT INT_VAR opcode = 139 type = 1 target = 2 parameter1 = 64285 timing = 9 resist_dispel = 2 probability1 = 10 savingthrow = 4 savebonus = ~-4~ END
      LPF ADD_ITEM_EFFECT INT_VAR opcode = 13 type = 1 target = 2 parameter1 = 0 parameter2 = 8 timing = 1 resist_dispel = 2 probability1 = 10 savingthrow = 4 savebonus = ~-4~ END
      LPF ADD_ITEM_EFFECT INT_VAR opcode = 141 type = 1 target = 2 parameter1 = 0 parameter2 = 39 timing = 1 resist_dispel = 2 probability1 = 10 savingthrow = 4 savebonus = ~-4~ END

      READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldtwohand2%~ ~%newtwohand2%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
END

///////////////////////////////////////////////////////////////////////////
// Greater Silver Sword                                                  //
// +4 weapon, -4 to save, immunity psionics                              //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~SW2H15.ITM~ BEGIN

    COPY_EXISTING ~SW2H15.ITM~ ~override\MO2H15.ITM~
      WRITE_LONG 0x60 4
      LPF ALTER_ITEM_HEADER INT_VAR header_type=1 thac0_bonus = 4 damage_bonus = 4 END
      LPF ALTER_ITEM_EFFECT INT_VAR match_opcode = ~-1~ check_headers = 1 savebonus = ~-4~ END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 267 target = 1 parameter1 = 14780 timing = 2 resist_dispel = 0 probability1 = 100 END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 267 target = 1 parameter1 = 14672 timing = 2 resist_dispel = 0 probability1 = 100 END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 267 target = 1 parameter1 = 8364 timing = 2 resist_dispel = 0 probability1 = 100 END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 267 target = 1 parameter1 = 14791 timing = 2 resist_dispel = 2 probability1 = 100 END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 267 target = 1 parameter1 = 14782 timing = 2 resist_dispel = 2 probability1 = 100 END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 142 target = 1 parameter2 = 52 timing = 2 resist_dispel = 2 probability1 = 100 END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 142 target = 1 parameter2 = 52 timing = 2 resist_dispel = 0 probability1 = 100 END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 101 target = 1 parameter2 = 5 timing = 2 resist_dispel = 0 probability1 = 100 END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 101 target = 1 parameter2 = 128 timing = 2 resist_dispel = 2 probability1 = 100 END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 296 target = 1 timing = 2 resist_dispel = 0 probability1 = 100 STR_VAR resource = ~spnwchrm~ END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 296 target = 1 timing = 2 resist_dispel = 2 probability1 = 100 STR_VAR resource = ~spflayer~ END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 296 target = 1 timing = 2 resist_dispel = 2 probability1 = 100 STR_VAR resource = ~spconfus~ END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 169 target = 1 parameter2 = 0 timing = 2 resist_dispel = 0 probability1 = 100 END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 169 target = 1 parameter2 = 1 timing = 2 resist_dispel = 0 probability1 = 100 END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 169 target = 1 parameter2 = 43 timing = 2 resist_dispel = 0 probability1 = 100 END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 169 target = 1 parameter2 = 47 timing = 2 resist_dispel = 2 probability1 = 100 END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 169 target = 1 parameter2 = 2 timing = 2 resist_dispel = 2 probability1 = 100 END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 169 target = 1 parameter2 = 3 timing = 2 resist_dispel = 2 probability1 = 100 END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 206 target = 1 timing = 2 resist_dispel = 2 probability1 = 100 STR_VAR resource = ~spin975~ END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 206 target = 1 timing = 2 resist_dispel = 2 probability1 = 100 STR_VAR resource = ~spin974~ END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 206 target = 1 timing = 2 resist_dispel = 2 probability1 = 100 STR_VAR resource = ~spin912~ END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 206 target = 1 timing = 2 resist_dispel = 2 probability1 = 100 STR_VAR resource = ~spin911~ END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 206 target = 1 timing = 2 resist_dispel = 2 probability1 = 100 STR_VAR resource = ~spin909~ END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 206 target = 1 timing = 2 resist_dispel = 2 probability1 = 100 STR_VAR resource = ~spin910~ END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 206 target = 1 timing = 2 resist_dispel = 2 probability1 = 100 STR_VAR resource = ~spin959~ END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 206 target = 1 timing = 2 resist_dispel = 2 probability1 = 100 STR_VAR resource = ~spin834~ END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 206 target = 1 timing = 2 resist_dispel = 2 probability1 = 100 STR_VAR resource = ~spin774~ END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 206 target = 1 timing = 2 resist_dispel = 2 probability1 = 100 STR_VAR resource = ~spin775~ END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 206 target = 1 timing = 2 resist_dispel = 2 probability1 = 100 STR_VAR resource = ~sppr709~ END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 206 target = 1 timing = 2 resist_dispel = 2 probability1 = 100 STR_VAR resource = ~spwi401~ END
      SAY NAME1 @31504
      SAY NAME2 @31504
      SAY DESC  @31505
END

///////////////////////////////////////////////////////////////////////////
// Dragon Blade +3                                                       //
// +1d6 cold (previously +1)                                             //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~BDSW2H01.ITM~ BEGIN
OUTER_SPRINT oldtwohand3 @31506
OUTER_SPRINT newtwohand3 @31507
    
    COPY_EXISTING ~BDSW2H01.ITM~ ~override~ 
        LPF ALTER_ITEM_EFFECT INT_VAR match_opcode = 12 check_headers = 1 parameter1 = 0 dicenumber = 1 dicesize = 6 END

        READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldtwohand3%~ ~%newtwohand3%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
END

///////////////////////////////////////////////////////////////////////////
// Gram the Sword of Grief +4                                            //
// +4 weapon (previously +5)                                             //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~SW2H17.ITM~ BEGIN
OUTER_SPRINT oldtwohand4 @31508
OUTER_SPRINT newtwohand4 @31509

    COPY_EXISTING ~SW2H17.ITM~ ~override~ 
      WRITE_LONG 0x60 4
      LPF ALTER_ITEM_HEADER INT_VAR header_type=1 thac0_bonus = 4 damage_bonus = 4 END

      PATCH_FOR_EACH offset IN 0xc 0x54 BEGIN
        READ_LONG ~%offset%~ desc_strref
            PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
              READ_STRREF ~%offset%~ desc
              INNER_PATCH_SAVE desc ~%desc%~ BEGIN
                REPLACE_TEXTUALLY ~%oldtwohand4%~ ~%newtwohand4%~
              END
              SAY_EVALUATED ~%offset%~ ~%desc%~
            END
      END
END

///////////////////////////////////////////////////////////////////////////
// Gram the Sword of Grief +5                                            //
// Hit target loses 1 point of Strength per hit for 5 rounds replaces    //
// Each hit target must save vs. Death or lose 1 level                   //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~SW2H18.ITM~ BEGIN
OUTER_SPRINT oldtwohand5 @31510
OUTER_SPRINT newtwohand5 @31511

    COPY_EXISTING ~SW2H18.ITM~ ~override~ 
      LPF DELETE_EFFECT INT_VAR header_type = 1 match_opcode = 216 END
      LPF DELETE_EFFECT INT_VAR header_type = 1 match_opcode = 139 END
      LPF ADD_ITEM_EFFECT INT_VAR opcode = 44 type = 1 target = 2 parameter1 = ~-1~ parameter2 = 0 timing = 0 resist_dispel = 2 duration = 30 probability1 = 100 END
      LPF ADD_ITEM_EFFECT INT_VAR opcode = 142 type = 1 target = 2 parameter2 = 91 timing = 0 resist_dispel = 2 duration = 30 probability1 = 100 END

      READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldtwohand5%~ ~%newtwohand5%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
END

///////////////////////////////////////////////////////////////////////////
// Joril's Dagger +3                                                     //
// +1d6 cold (previously +1)                                             //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~WAS2H.ITM~ BEGIN
OUTER_SPRINT oldtwohand3 @31506
OUTER_SPRINT newtwohand3 @31507
    
    COPY_EXISTING ~WAS2H.ITM~ ~override~ 
        LPF ALTER_ITEM_EFFECT INT_VAR match_opcode = 12 check_headers = 1 parameter1 = 0 dicenumber = 1 dicesize = 6 END

        READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldtwohand3%~ ~%newtwohand3%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
END

///////////////////////////////////////////////////////////////////////////
// The World's Edge +3                                                   //
// On a critical hit, the wielder gains +1 Strength bonus for 2 rounds   // 
// (non-cumulative)                                                      //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~SW2H07.ITM~ BEGIN
COPY ~forgotten-armament/spl/update_item/MO2H07.SPL~ ~override~
OUTER_SPRINT oldtwohand6 @31512
OUTER_SPRINT newtwohand6 @31513
    
    COPY_EXISTING ~SW2H07.ITM~ ~override~ 
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 341 target = 1 parameter2 = 1 timing = 2 resist_dispel = 0 probability1 = 100 STR_VAR resource = ~MO2H07~ END

      READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldtwohand6%~ ~%newtwohand6%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
END

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Wakizashi                                                             //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Yamato +4                                                             //
// +1 APR                                                                //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~SW1H66.ITM~ BEGIN
OUTER_SPRINT oldyamato @31600
OUTER_SPRINT newyamato @31601

    COPY_EXISTING ~SW1H66.ITM~ ~override~ 
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 1 target = 1 parameter1 = 1 parameter2 = 0 timing = 2 resist_dispel = 0 probability1 = 100 END

      READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldyamato%~ ~%newyamato%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
END

///////////////////////////////////////////////////////////////////////////
// Kachiko's Wakizashi +3                                                //
// Increase duration of drain from round to turns                        //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~WAWAK.ITM~ BEGIN
OUTER_SPRINT oldwaki1 @31602
OUTER_SPRINT newwaki1 @31603

    COPY_EXISTING ~WAWAK.ITM~ ~override~ 
      LPF ALTER_ITEM_EFFECT INT_VAR match_opcode = 142 check_headers = 1 duration = 120 END
      LPF ALTER_ITEM_EFFECT INT_VAR match_opcode = 49 check_headers = 1 duration = 120 END

      READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldwaki1%~ ~%newwaki1%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
END

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// War Hammer                                                            //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Ashideena +2                                                          //
// +1d4 electrical damage (previously +1)                                //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~HAMM03.ITM~ BEGIN
OUTER_SPRINT oldhamm1 @31700
OUTER_SPRINT newhamm1 @31701

    COPY_EXISTING ~HAMM03.ITM~ ~override~
      LPF ALTER_ITEM_EFFECT INT_VAR check_headers = 1 match_opcode = 12 parameter1 = 0 dicenumber = 1 dicesize = 4 END

      READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldhamm1%~ ~%newhamm1%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
END

///////////////////////////////////////////////////////////////////////////
// Borok's Fist +2                                                       //
// +1d4 electrical damage (previously +1)                                //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~HAMM05.ITM~ BEGIN
OUTER_SPRINT oldhamm1 @31700
OUTER_SPRINT newhamm1 @31701

    COPY_EXISTING ~HAMM05.ITM~ ~override~
      LPF ALTER_ITEM_EFFECT INT_VAR check_headers = 1 match_opcode = 12 parameter1 = 0 dicenumber = 1 dicesize = 4 END

      READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldhamm1%~ ~%newhamm1%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
END

/*
///////////////////////////////////////////////////////////////////////////
// Crom Faeyr +5                                                         //
// +2d4+1 electrical damage (previously +5)                              //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~HAMM09.ITM~ BEGIN
OUTER_SPRINT oldhamm2 @31702
OUTER_SPRINT newhamm2 @31703

    COPY_EXISTING ~HAMM09.ITM~ ~override~
      LPF ALTER_ITEM_EFFECT INT_VAR check_headers = 1 match_opcode = 12 parameter1 = 1 dicenumber = 2 dicesize = 4 END

      READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldhamm2%~ ~%newhamm2%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
END
*/

///////////////////////////////////////////////////////////////////////////
// Hammer of Thunderbolts +3                                             //
// +1d6 electrical damage                                                //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~HAMM07.ITM~ BEGIN
OUTER_SPRINT oldhamm3 @31704
OUTER_SPRINT newhamm3 @31705

    COPY_EXISTING ~HAMM07.ITM~ ~override~
      LPF ADD_ITEM_EFFECT INT_VAR opcode = 12 type = 1 target = 2 parameter1 = 0 parameter2 = 262144 timing = 1 resist_dispel = 0 probability1 = 100 dicenumber = 1 dicesize = 6 END

      READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldhamm3%~ ~%newhamm3%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
END

///////////////////////////////////////////////////////////////////////////
// Rifthammer +3                                                         //
// +1d6 fire damage (previously +1d4)                                    //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~MOHM02.ITM~ BEGIN
OUTER_SPRINT oldhamm4 @31706
OUTER_SPRINT newhamm4 @31707

    COPY_EXISTING ~MOHM02.ITM~ ~override~
      LPF ALTER_ITEM_EFFECT INT_VAR check_headers = 1 match_opcode = 12 parameter1 = 0 dicenumber = 1 dicesize = 6 END

      READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldhamm4%~ ~%newhamm4%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
END

/*************************************************************************/
///////////////////////////////////////////////////////////////////////////
// UPDATE RANGED WEAPONS                                                 //
///////////////////////////////////////////////////////////////////////////
/*************************************************************************/

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Longbow                                                               //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Elven Court Bow                                                       //
// +3 Thac0 (previously +4) and +3 Damage (missile)                      //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~BOW12.ITM~ BEGIN
OUTER_SPRINT oldlbow1 @31900
OUTER_SPRINT newlbow1 @31901

    COPY_EXISTING ~BOW12.ITM~ ~override~
      LPF ALTER_ITEM_HEADER INT_VAR header_type=4 thac0_bonus = 3 damage_bonus = 3 END

      READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldlbow1%~ ~%newlbow1%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
END

///////////////////////////////////////////////////////////////////////////
// Ripper +2                                                             //
// +4 missile Damage (previously +2)                                     //
// Immunity to Charm and Confusion                                       //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~BOW09.ITM~ BEGIN
OUTER_SPRINT oldlbow2 @31902
OUTER_SPRINT newlbow2 @31903
OUTER_SPRINT oldlbow3 @31904
OUTER_SPRINT newlbow3 @31905

    COPY_EXISTING ~BOW09.ITM~ ~override~
      LPF ALTER_ITEM_HEADER INT_VAR header_type=4 damage_bonus = 4 END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 267 target = 1 parameter1 = 8364 timing = 2 resist_dispel = 0 probability1 = 100 END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 267 target = 1 parameter1 = 14780 timing = 2 resist_dispel = 0 probability1 = 100 END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 267 target = 1 parameter1 = 14672 timing = 2 resist_dispel = 0 probability1 = 100 END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 267 target = 1 parameter1 = 14791 timing = 2 resist_dispel = 0 probability1 = 100 END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 267 target = 1 parameter1 = 14782 timing = 2 resist_dispel = 0 probability1 = 100 END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 142 target = 1 parameter2 = 52 timing = 2 resist_dispel = 0 probability1 = 100 END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 101 target = 1 parameter2 = 5 timing = 2 resist_dispel = 0 probability1 = 100 END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 101 target = 1 parameter2 = 128 timing = 2 resist_dispel = 0 probability1 = 100 END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 296 target = 1 timing = 2 resist_dispel = 0 probability1 = 100 STR_VAR resource = ~spnwchrm~ END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 296 target = 1 timing = 2 resist_dispel = 0 probability1 = 100 STR_VAR resource = ~spconfus~ END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 169 target = 1 parameter2 = 47 timing = 2 resist_dispel = 0 probability1 = 100 END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 169 target = 1 parameter2 = 2 timing = 2 resist_dispel = 0 probability1 = 100 END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 169 target = 1 parameter2 = 0 timing = 2 resist_dispel = 0 probability1 = 100 END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 169 target = 1 parameter2 = 1 timing = 2 resist_dispel = 0 probability1 = 100 END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 169 target = 1 parameter2 = 43 timing = 2 resist_dispel = 0 probability1 = 100 END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 169 target = 1 parameter2 = 3 timing = 2 resist_dispel = 0 probability1 = 100 END

      READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldlbow2%~ ~%newlbow2%~
              REPLACE_TEXTUALLY ~%oldlbow3%~ ~%newlbow3%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
END

///////////////////////////////////////////////////////////////////////////
// Taralash +4                                                           //
// +4 Thac0 (previously +5) and +4 Damage (missile)                      //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~BOW22.ITM~ BEGIN
OUTER_SPRINT oldlbow4 @31906
OUTER_SPRINT newlbow4 @31907

    COPY_EXISTING ~BOW22.ITM~ ~override~
      LPF ALTER_ITEM_HEADER INT_VAR header_type=4 thac0_bonus = 4 damage_bonus = 4 END

      READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldlbow4%~ ~%newlbow4%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
END

///////////////////////////////////////////////////////////////////////////
// Taralash +5                                                           //
// +5 Thac0 (previously +6) and +5 Damage (missile)                      //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~BOW23.ITM~ BEGIN
OUTER_SPRINT oldlbow5 @31908
OUTER_SPRINT newlbow5 @31909
OUTER_SPRINT oldlbow6 @31911
OUTER_SPRINT newlbow6 @31912
OUTER_SPRINT oldlbow7 @31913
OUTER_SPRINT newlbow7 @31914
OUTER_SET arow01_name = RESOLVE_STR_REF (@31910)

    COPY_EXISTING ~arow01.itm~ ~override~
      READ_LONG 0x64 abil_off       
      READ_ASCII (abil_off       ) "ability" (56) // read in whole ability
      READ_SHORT (abil_off + 0x1e) "fx_num"
      PATCH_IF ("fx_num" != 0) BEGIN
        READ_SHORT  (abil_off + 0x20) "fx_idx"
        READ_LONG 0x6a fx_off
        READ_ASCII (fx_off + (fx_idx * 0x30)) "effects" (fx_num * 0x30)
      END ELSE BEGIN
        SPRINT "effects" ""
      END
      PATCH_IF ("%SOURCE_RES%" STRING_COMPARE_CASE "arow01" = 0) BEGIN
        SPRINT arow01_ability "%ability%"
        SPRINT arow01_effects "%effects%"
        SET    arow01_fx_num = fx_num
      END

    COPY_EXISTING ~BOW23.ITM~ ~override~
      SPRINT ability "%arow01_ability%"
      SPRINT imported_effects "%arow01_effects%" 
      SET imported_fx_num = "%arow01_fx_num%"
      SET name = "%arow01_name%"
      READ_LONG   0x64 abil_off
      READ_SHORT  0x68 abil_num
      SET inserted = 0
      SET new_fx = 0
      FOR (index = 0 ; index < abil_num ; ++index) BEGIN
        PATCH_IF inserted BEGIN 
          WRITE_SHORT (abil_off + 0x20 + (index * 0x38)) (THIS + new_fx) // if already inserted, just correct the effect index
        END ELSE BEGIN
          READ_BYTE (abil_off +        (index * 0x38)) type
          PATCH_IF type = 4 BEGIN // insert before first launcher type
            READ_SHORT (abil_off + 0x1e + (index * 0x38)) abil_fx_num
            READ_SHORT (abil_off + 0x20 + (index * 0x38)) abil_fx_idx
            SET abil_num += 1
            SET inserted = 1
            SET new_fx = abil_fx_num + imported_fx_num
            PATCH_IF (index < 2) BEGIN // for adjusting tooltip
              DEFINE_ASSOCIATIVE_ARRAY cd_abil_table BEGIN "%SOURCE_RES%","%name%","%index%" => 0 END
            END  
            PATCH_IF new_fx BEGIN // if we also clone existing effects
              READ_LONG 0x6a fx_off
              PATCH_IF abil_fx_num BEGIN // if we also need to clone existing effects
                READ_ASCII   (fx_off + (abil_fx_idx * 0x30)) effects (abil_fx_num * 0x30)
                INSERT_BYTES (fx_off + (abil_fx_idx * 0x30)) (abil_fx_num * 0x30) // create new effect(s)
                WRITE_ASCIIE (fx_off + (abil_fx_idx * 0x30)) "%effects%"          // write in info
              END    
              PATCH_IF imported_fx_num BEGIN // if we also clone existing effects
                INSERT_BYTES (fx_off + (abil_fx_idx * 0x30)) (imported_fx_num * 0x30) // create new effect(s)
                WRITE_ASCIIE (fx_off + (abil_fx_idx * 0x30)) "%imported_effects%"     // write in info
              END     
            END   
            INSERT_BYTES (abil_off +        (index * 0x38)) 0x38        // create new ability
            WRITE_ASCIIE (abil_off +        (index * 0x38)) "%ability%" // write in info
            WRITE_BYTE   (abil_off + 0x10 + (index * 0x38)) 0           // no launcher required
            WRITE_SHORT  (abil_off + 0x1e + (index * 0x38)) new_fx      // combine existing + imported effects
            WRITE_SHORT  (abil_off + 0x20 + (index * 0x38)) abil_fx_idx // use correct index
            WRITE_SHORT  (abil_off + 0x22 + (index * 0x38)) 0           // no charges             
          END 
        END
      END
      PATCH_IF inserted BEGIN
        WRITE_SHORT 0x68 abil_num
        WRITE_LONG  0x6a (THIS + 0x38)
      END
      LPF ALTER_ITEM_HEADER INT_VAR header_type = 4 thac0_bonus = 5 damage_bonus = 5 dicenumber = 1 projectile = 102 END
      LPF ADD_ITEM_EFFECT INT_VAR opcode = 12 type = 4 target = 2 parameter1 = 2 parameter2 = 4194304 timing = 1 resist_dispel = 0 probability1 = 100 END
      LPF ADD_ITEM_EFFECT INT_VAR opcode = 12 type = 2 target = 2 parameter1 = 2 parameter2 = 4194304 timing = 1 resist_dispel = 0 probability1 = 100 END
      LPF ALTER_ITEM_HEADER INT_VAR header_type = 2 thac0_bonus = 5 damage_bonus = 5 dicenumber = 1 projectile = 102 END

      READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldlbow5%~ ~%newlbow5%~
              REPLACE_TEXTUALLY ~%oldlbow6%~ ~%newlbow6%~
              REPLACE_TEXTUALLY ~%oldlbow7%~ ~%newlbow7%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END

END

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Shortbow                                                              //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Protector of the Dryads +2                                            //
// +10% to Detect Illusions and Find Traps                               //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~BOW08.ITM~ BEGIN
OUTER_SPRINT oldsbow1 @32000
OUTER_SPRINT newsbow1 @32001
    
    COPY_EXISTING ~BOW08.ITM~ ~override~
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 276 target = 1 parameter1 = 10 parameter2 = 0 timing = 2 resist_dispel = 2 probability1 = 100 END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 91 target = 1 parameter1 = 10 parameter2 = 0 timing = 2 resist_dispel = 2 probability1 = 100 END

      READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldsbow1%~ ~%newsbow1%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
END

/*************************************************************************/
///////////////////////////////////////////////////////////////////////////
// UPDATE ARMOR                                                          //
///////////////////////////////////////////////////////////////////////////
/*************************************************************************/

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Robe                                                                  //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Adventurer's Robe                                                     //
// Remove Armor Class vs. Crushing Bonus and save vs. petrification      //
// +5% Damage Resistance to all physical damage                          //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~CLCK14.ITM~ BEGIN
OUTER_SPRINT oldrobe1 @32200
OUTER_SPRINT newrobe1 @32201
OUTER_SPRINT oldrobe2 @32202
OUTER_SPRINT newrobe2 @32203
  
    COPY_EXISTING ~CLCK14.ITM~ ~override~
      LPF DELETE_ITEM_EQEFFECT INT_VAR opcode_to_delete = 0 END
      LPF DELETE_ITEM_EQEFFECT INT_VAR opcode_to_delete = 35 END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 86 target = 1 parameter1 = 5 parameter2 = 0 timing = 2 resist_dispel = 2 probability1 = 100 END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 87 target = 1 parameter1 = 5 parameter2 = 0 timing = 2 resist_dispel = 2 probability1 = 100 END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 88 target = 1 parameter1 = 5 parameter2 = 0 timing = 2 resist_dispel = 2 probability1 = 100 END

      READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldrobe1%~ ~%newrobe1%~
              REPLACE_TEXTUALLY ~%oldrobe2%~ ~%newrobe2%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
END

///////////////////////////////////////////////////////////////////////////
// Robes of the Archmagi                                                 //
// +5 Bonus to AC (previously set AC to 5)                               //
// +10% Magic Resistance (previously +5%)                                //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~CLCK15.ITM~ OR FILE_EXISTS_IN_GAME ~CLCK16.ITM~ OR FILE_EXISTS_IN_GAME ~CLCK17.ITM~ BEGIN
OUTER_SPRINT oldrobe3 @32204
OUTER_SPRINT newrobe3 @32205
OUTER_SPRINT oldrobe4 @32206
OUTER_SPRINT newrobe4 @32207

    ACTION_FOR_EACH robe IN 5 6 7 BEGIN
      ACTION_IF FILE_EXISTS_IN_GAME ~CLCK1%robe%.ITM~ BEGIN
        COPY_EXISTING ~CLCK1%robe%.ITM~ ~override~
          //LPF ALTER_ITEM_EFFECT INT_VAR check_globals = 1 match_opcode = 0 parameter2 = 0 END
          LPF ALTER_ITEM_EFFECT INT_VAR check_globals = 1 match_opcode = 166 parameter1 = 10 END

          READ_LONG 0x54 desc_strref
              PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
                READ_STRREF 0x54 desc
                INNER_PATCH_SAVE desc ~%desc%~ BEGIN
                  //REPLACE_TEXTUALLY ~%oldrobe3%~ ~%newrobe3%~
                  REPLACE_TEXTUALLY ~%oldrobe4%~ ~%newrobe4%~
                END
                SAY_EVALUATED 0x54 ~%desc%~
              END
      END
    END
END

/*
///////////////////////////////////////////////////////////////////////////
// Robes of Vecna                                                        //
// +3 Bonus to AC (previously set AC to 5)                               //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~WA2ROBE.ITM~ BEGIN
OUTER_SPRINT oldrobe5 @32208
OUTER_SPRINT newrobe5 @32209

    COPY_EXISTING ~WA2ROBE.ITM~ ~override~
      LPF ALTER_ITEM_EFFECT INT_VAR check_globals = 1 match_opcode = 0 parameter1 = 3 parameter2 = 0 END

      READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldrobe5%~ ~%newrobe5%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
END
*/

///////////////////////////////////////////////////////////////////////////
// Traveler's Robe                                                       //
// +1 AC, +5% Magic Resistance                                           //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~CLCK13.ITM~ BEGIN
OUTER_SPRINT oldrobe6 @32210
OUTER_SPRINT newrobe6 @32211
OUTER_SPRINT oldrobe7 @32212
OUTER_SPRINT newrobe7 @32213

    COPY_EXISTING ~CLCK13.ITM~ ~override~
      LPF DELETE_ITEM_EQEFFECT INT_VAR opcode_to_delete = 36 END
      LPF ALTER_ITEM_EFFECT INT_VAR check_globals = 1 match_opcode = 0 parameter2 = 0 END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 166 target = 1 parameter1 = 5 parameter2 = 0 timing = 2 resist_dispel = 0 probability1 = 100 END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 142 target = 1 parameter2 = 63 timing = 2 resist_dispel = 0 probability1 = 100 END

      READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldrobe6%~ ~%newrobe6%~
              REPLACE_TEXTUALLY ~%oldrobe7%~ ~%newrobe7%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
END

///////////////////////////////////////////////////////////////////////////
// Knave's Robe                                                          //
// 10% chance of turning invisible when hit, Non-Detection               //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~CLCK12.ITM~ OR FILE_EXISTS_IN_GAME ~CLCK18.ITM~ BEGIN
OUTER_SPRINT oldrobe8 @32214
OUTER_SPRINT newrobe8 @32215
OUTER_SPRINT oldrobe9 @32216
OUTER_SPRINT newrobe9 @32217

    ACTION_FOR_EACH robe IN 2 8 BEGIN
      ACTION_IF FILE_EXISTS_IN_GAME ~CLCK1%robe%.ITM~ BEGIN
        COPY_EXISTING ~CLCK1%robe%.ITM~ ~override~
          LPF DELETE_ITEM_EQEFFECT INT_VAR opcode_to_delete = 0 END
          LPF DELETE_ITEM_EQEFFECT INT_VAR opcode_to_delete = 33 END
          LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 232 target = 1 parameter1 = 0 parameter2 = 0 timing = 2 resist_dispel = 0 probability1 = 9 STR_VAR resource = ~spwi206~ END
          LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 142 target = 1 parameter2 = 31 timing = 2 resist_dispel = 0 probability1 = 100 END
          LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 69 target = 1 timing = 2 resist_dispel = 0 probability1 = 100 END

          READ_LONG 0x54 desc_strref
              PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
                READ_STRREF 0x54 desc
                INNER_PATCH_SAVE desc ~%desc%~ BEGIN
                  REPLACE_TEXTUALLY ~%oldrobe8%~ ~%newrobe8%~
                  REPLACE_TEXTUALLY ~%oldrobe9%~ ~%newrobe9%~
                END
                SAY_EVALUATED 0x54 ~%desc%~
              END
      END
    END
END

///////////////////////////////////////////////////////////////////////////
// Shadow Armor +3                                                       //
// Move Silently: +15%                                                   //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~LEAT08.ITM~ BEGIN
OUTER_SPRINT oldleat1 @32400
OUTER_SPRINT newleat1 @32401

    COPY_EXISTING ~LEAT08.ITM~ ~override~
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 59 target = 1 parameter1 = 15 parameter2 = 0 timing = 2 resist_dispel = 2 probability1 = 100 END

      READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldleat1%~ ~%newleat1%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
END

///////////////////////////////////////////////////////////////////////////
// Armor of the Deep Night +4                                            //
// Hide in Shadows and Move Silently: +10%                               //
// Backstab Multiplier: +1 (Thieves only)                                //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~LEAT17.ITM~ BEGIN
COPY ~forgotten-armament/eff/update_item/MO1H10.EFF~ ~override/MOLT17.EFF~
OUTER_SPRINT oldleat2 @32402
OUTER_SPRINT newleat2 @32403

    COPY_EXISTING ~LEAT17.ITM~ ~override~
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 275 target = 1 parameter1 = 10 parameter2 = 0 timing = 2 resist_dispel = 2 probability1 = 100 END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 59 target = 1 parameter1 = 10 parameter2 = 0 timing = 2 resist_dispel = 2 probability1 = 100 END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 177 target = 1 parameter1 = 205 parameter2 = 5 timing = 2 resist_dispel = 0 probability1 = 100 STR_VAR resource = ~molt17~ END

      READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldleat2%~ ~%newleat2%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
END

///////////////////////////////////////////////////////////////////////////
// Karajah's Life and Death +3                                           //
// Movement rate increased by 2                                          //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~LEAT09.ITM~ BEGIN
OUTER_SPRINT oldleat3 @32404
OUTER_SPRINT newleat3 @32405

    COPY_EXISTING ~LEAT09.ITM~ ~override~
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 126 target = 1 parameter1 = 2 parameter2 = 0 timing = 2 resist_dispel = 2 probability1 = 100 END

      READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldleat3%~ ~%newleat3%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
END

/*
///////////////////////////////////////////////////////////////////////////
// Protector of the Second                                               //
//                                           //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~LEAT03.ITM~ BEGIN
OUTER_SPRINT oldleat4 @32406
OUTER_SPRINT newleat4 @32407

    COPY_EXISTING ~LEAT03.ITM~ ~override~
      //LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 126 target = 1 parameter1 = 2 parameter2 = 0 timing = 2 resist_dispel = 2 probability1 = 100 END

      READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldleat4%~ ~%newleat4%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
END
*/

///////////////////////////////////////////////////////////////////////////
// ALL Elven Chain                                                       //
// Saving Throws: +1                                                     //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~CHAN12.ITM~ OR FILE_EXISTS_IN_GAME ~CHAN13.ITM~ OR FILE_EXISTS_IN_GAME ~CHAN14.ITM~ OR FILE_EXISTS_IN_GAME ~CHAN15.ITM~ OR FILE_EXISTS_IN_GAME ~CHAN16.ITM~ OR FILE_EXISTS_IN_GAME ~CHAN19.ITM~ BEGIN
OUTER_SPRINT oldchain1 @32600
OUTER_SPRINT newchain1 @32601

    ACTION_FOR_EACH chain IN 2 3 4 5 6 9 BEGIN
      ACTION_IF FILE_EXISTS_IN_GAME ~CHAN1%chain%.ITM~ BEGIN
        COPY_EXISTING ~CHAN1%chain%.ITM~ ~override~
          LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 33 target = 1 parameter1 = 1 parameter2 = 0 timing = 2 resist_dispel = 0 probability1 = 100 END
          LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 34 target = 1 parameter1 = 1 parameter2 = 0 timing = 2 resist_dispel = 0 probability1 = 100 END
          LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 35 target = 1 parameter1 = 1 parameter2 = 0 timing = 2 resist_dispel = 0 probability1 = 100 END
          LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 36 target = 1 parameter1 = 1 parameter2 = 0 timing = 2 resist_dispel = 0 probability1 = 100 END
          LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 37 target = 1 parameter1 = 1 parameter2 = 0 timing = 2 resist_dispel = 0 probability1 = 100 END

          PATCH_FOR_EACH offset IN 0x50 0x54 BEGIN
            READ_LONG ~%offset%~ desc_strref
                PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
                  READ_STRREF ~%offset%~ desc
                  INNER_PATCH_SAVE desc ~%desc%~ BEGIN
                    REPLACE_TEXTUALLY ~%oldchain1%~ ~%newchain1%~
                  END
                  SAY_EVALUATED ~%offset%~ ~%desc%~
                END
          END
      END
    END
END

///////////////////////////////////////////////////////////////////////////
// Melodic Chain +3                                                      //
// Vocalize and Longer Bard Song                                         //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~CHAN15.ITM~ BEGIN
OUTER_SPRINT oldchain2 @32602
OUTER_SPRINT newchain2 @32603
OUTER_SET silenced = RESOLVE_STR_REF (@31310)
OUTER_SET silence = RESOLVE_STR_REF (@31311)
    
    COPY_EXISTING ~CHAN15.ITM~ ~override~
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 206 target = 1 timing = 2 resist_dispel = 0 probability1 = 100 STR_VAR resource = ~spin998~ END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 206 target = 1 timing = 2 resist_dispel = 0 probability1 = 100 STR_VAR resource = ~spin692~ END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 206 target = 1 timing = 2 resist_dispel = 0 probability1 = 100 STR_VAR resource = ~sppr988~ END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 206 target = 1 timing = 2 resist_dispel = 0 probability1 = 100 STR_VAR resource = ~sppr211~ END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 206 target = 1 timing = 2 resist_dispel = 0 probability1 = 100 STR_VAR resource = ~spwi612~ END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 206 target = 1 timing = 2 resist_dispel = 0 probability1 = 100 STR_VAR resource = ~spwi223~ END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 169 target = 1 parameter2 = 112 timing = 2 resist_dispel = 0 probability1 = 100 END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 142 target = 1 parameter2 = 103 timing = 2 resist_dispel = 0 probability1 = 100 END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 169 target = 1 parameter2 = 34 timing = 2 resist_dispel = 0 probability1 = 100 END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 101 target = 1 parameter2 = 80 timing = 2 resist_dispel = 0 probability1 = 100 END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 101 target = 1 parameter2 = 38 timing = 2 resist_dispel = 0 probability1 = 100 END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 81 target = 1 timing = 1 resist_dispel = 0 probability1 = 100 END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 48 target = 1 timing = 1 resist_dispel = 0 probability1 = 100 END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 267 target = 1 parameter1 = ~%silenced%~ timing = 2 resist_dispel = 2 probability1 = 100 END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 267 target = 1 parameter1 = ~%silence%~ timing = 2 resist_dispel = 2 probability1 = 100 END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 99 target = 1 parameter1 = 300 parameter2 = 2 timing = 2 resist_dispel = 0 probability1 = 100 END

      READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldchain2%~ ~%newchain2%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
END

///////////////////////////////////////////////////////////////////////////
// Sylvan Chain +2                                                       //
// Movement rate increased by 2 and Improves casting speed by 1          //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~CHAN14.ITM~ BEGIN
OUTER_SPRINT oldchain3 @32604
OUTER_SPRINT newchain3 @32605
    
    COPY_EXISTING ~CHAN14.ITM~ ~override~
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 126 target = 1 parameter1 = 2 parameter2 = 0 timing = 2 resist_dispel = 2 probability1 = 100 END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 189 target = 1 parameter1 = 1 parameter2 = 0 timing = 2 resist_dispel = 2 probability1 = 100 END

      READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldchain3%~ ~%newchain3%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
END

///////////////////////////////////////////////////////////////////////////
// Aslyferund Elven Chain +5                                             //
// Remove Immunity to normal weapons, +10% Damage resistance             //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~CHAN19.ITM~ BEGIN
OUTER_SPRINT oldchain4 @32606
OUTER_SPRINT newchain4 @32607
OUTER_SPRINT oldchain5 @32608
OUTER_SPRINT newchain5 @32609
    
    COPY_EXISTING ~CHAN19.ITM~ ~override~
      LPF DELETE_ITEM_EQEFFECT INT_VAR opcode_to_delete = 120 END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 86 target = 1 parameter1 = 10 parameter2 = 0 timing = 2 resist_dispel = 2 probability1 = 100 END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 87 target = 1 parameter1 = 10 parameter2 = 0 timing = 2 resist_dispel = 2 probability1 = 100 END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 88 target = 1 parameter1 = 10 parameter2 = 0 timing = 2 resist_dispel = 2 probability1 = 100 END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 89 target = 1 parameter1 = 10 parameter2 = 0 timing = 2 resist_dispel = 2 probability1 = 100 END

      READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldchain4%~ ~%newchain4%~
              REPLACE_TEXTUALLY ~%oldchain5%~ ~%newchain5%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
END

///////////////////////////////////////////////////////////////////////////
// Jester's Chain +4                                                     //
// Remove Immunity to normal weapons, +10% Damage resistance             //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~CHAN10.ITM~ BEGIN
OUTER_SPRINT oldchain6 @32610
OUTER_SPRINT newchain6 @32611
    
    COPY_EXISTING ~CHAN10.ITM~ ~override~
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 142 target = 1 parameter2 = 27 timing = 2 resist_dispel = 2 probability1 = 100 END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 142 target = 1 parameter2 = 26 timing = 2 resist_dispel = 2 probability1 = 100 END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 30 target = 1 parameter1 = 10 parameter2 = 0 timing = 2 resist_dispel = 0 probability1 = 100 END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 29 target = 1 parameter1 = 10 parameter2 = 0 timing = 2 resist_dispel = 0 probability1 = 100 END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 28 target = 1 parameter1 = 10 parameter2 = 0 timing = 2 resist_dispel = 0 probability1 = 100 END

      READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldchain6%~ ~%newchain6%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
END

///////////////////////////////////////////////////////////////////////////
// Crimson Chain +5                                                      //
//              //
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Mail of the Dead +2                                                   //
//             //
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Ashen Scales +2                                                       //
// Save vs. Paralyze/Poison/Death: +4                                    //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~CHAN17.ITM~ BEGIN
OUTER_SPRINT oldsplint1 @32700
OUTER_SPRINT newsplint1 @32701

    COPY_EXISTING ~CHAN17.ITM~ ~override~
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 33 target = 1 parameter1 = 4 parameter2 = 0 timing = 2 resist_dispel = 0 probability1 = 100 END

      READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldsplint1%~ ~%newsplint1%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
END

///////////////////////////////////////////////////////////////////////////
// Plate of Balduran                                                     //
// Remove Hit Point Bonus                                                //
// Charisma: +3 (previously +1) and Regenerate 1 Hit Point per round     //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~WA2PLAT.ITM~ BEGIN
OUTER_SPRINT oldplate1 @32900
OUTER_SPRINT newplate1 @32901

    COPY_EXISTING ~WA2PLAT.ITM~ ~override~
      LPF DELETE_ITEM_EQEFFECT INT_VAR opcode_to_delete = 18 END
      LPF ALTER_ITEM_EFFECT INT_VAR check_globals = 1 match_opcode = 6 parameter1 = 3 END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 142 target = 1 parameter2 = 87 timing = 2 resist_dispel = 0 probability1 = 100 END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 89 target = 1 parameter1 = 6 parameter2 = 3 timing = 2 resist_dispel = 0 probability1 = 100 END

      READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldplate1%~ ~%newplate1%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
END

/*************************************************************************/
///////////////////////////////////////////////////////////////////////////
// UPDATE SHIELDS                                                        //
///////////////////////////////////////////////////////////////////////////
/*************************************************************************/

/*************************************************************************/
///////////////////////////////////////////////////////////////////////////
// UPDATE ACCESSORIES                                                    //
///////////////////////////////////////////////////////////////////////////
/*************************************************************************/


// Bracers: Mintassan's Miraculous Bracers, Red Guard, Clasps of the Devoted, Bracers of the Inner Planes