// Forgotten Armament - Update Existing Items

/*************************************************************************/
///////////////////////////////////////////////////////////////////////////
// UPDATE MELEE WEAPONS                                                  //
///////////////////////////////////////////////////////////////////////////
/*************************************************************************/

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Axe                                                                   //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Mauletar +2                                                           //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~AX1H03.ITM~ BEGIN
    COPY ~forgotten-armament/itm/update/AX1H03.ITM~ ~override~
        SAY NAME1 @10000
        SAY NAME2 @30000
        SAY UNIDENTIFIED_DESC @10001
        SAY DESC @30001
END

///////////////////////////////////////////////////////////////////////////
// Azuredge                                                              //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~AX1H10.ITM~ BEGIN
    COPY ~forgotten-armament/itm/update/AX1H10.ITM~ ~override~
END

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Dagger                                                                //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Dagger of <CHARNAME>                                                  //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~DAGG19.ITM~ BEGIN
OUTER_SPRINT olddagger1 @30300
OUTER_SPRINT olddagger2 @30302
OUTER_SPRINT newdagger1 @30301
OUTER_SPRINT newdagger2 @30303

    COPY_EXISTING ~DAGG19.ITM~ ~override~
        WRITE_LONG 0x60 2
        LPF ALTER_ITEM_HEADER INT_VAR header_type=1 thac0_bonus = 2 damage_bonus = 2 END
        LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 142 target = 1 parameter2 = 63 timing = 2 resist_dispel = 2 probability1 = 100 END 
        LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 166 target = 1 parameter1 = 10 parameter2 = 0 timing = 2 resist_dispel = 0 probability1 = 100 END 
        LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 42 target = 1 parameter1 = 10 parameter2 = 2 timing = 2 resist_dispel = 0 probability1 = 100 END
        LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 42 target = 1 parameter1 = 10 parameter2 = 1 timing = 2 resist_dispel = 0 probability1 = 100 END
        LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 42 target = 1 parameter1 = 10 parameter2 = 0 timing = 2 resist_dispel = 0 probability1 = 100 END 

        READ_LONG 0x50 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x50 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%olddagger1%~ ~%newdagger1%~
              REPLACE_TEXTUALLY ~%olddagger2%~ ~%newdagger2%~
            END
            SAY_EVALUATED 0x50 ~%desc%~
          END
END

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Flails                                                                //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Flail of Ages +5                                                      //
// Remove Magic Resistance and Free Action                               //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~BLUN30.ITM~ BEGIN
OUTER_SPRINT oldflail1 @30400

    COPY_EXISTING ~BLUN30.ITM~ ~override~
        LPF DELETE_ITEM_EQEFFECT INT_VAR opcode_to_delete = 46 END
        LPF DELETE_ITEM_EQEFFECT INT_VAR opcode_to_delete = 267 END
        LPF DELETE_ITEM_EQEFFECT INT_VAR opcode_to_delete = 142 END
        LPF DELETE_ITEM_EQEFFECT INT_VAR opcode_to_delete = 163 END
        LPF DELETE_ITEM_EQEFFECT INT_VAR opcode_to_delete = 101 END
        LPF DELETE_ITEM_EQEFFECT INT_VAR opcode_to_delete = 296 END
        LPF DELETE_ITEM_EQEFFECT INT_VAR opcode_to_delete = 166 END
        LPF DELETE_ITEM_EQEFFECT INT_VAR opcode_to_delete = 126 END
        LPF DELETE_ITEM_EQEFFECT INT_VAR opcode_to_delete = 169 END
        LPF DELETE_ITEM_EQEFFECT INT_VAR opcode_to_delete = 206 END
        LPF DELETE_ITEM_EQEFFECT INT_VAR opcode_to_delete = 162 END
        LPF DELETE_ITEM_EQEFFECT INT_VAR opcode_to_delete = 240 END

        READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldflail1%~ ~~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
END

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Halberd                                                               //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Suryris Blade                                                         //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~HALB03.ITM~ BEGIN
OUTER_SPRINT oldhalb1 @30500
OUTER_SPRINT newhalb1 @30501

    COPY_EXISTING ~HALB03.ITM~ ~override~
        LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 0 target = 1 parameter1 = 1 parameter2 = 0 timing = 2 resist_dispel = 2 probability1 = 100 END

        READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldhalb1%~ ~%newhalb1%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
END

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Katana                                                                //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Crimson Dawn                                                          //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~BDSW1H01.ITM~ BEGIN
OUTER_SPRINT oldkata4 @30606
OUTER_SPRINT newkata4 @30607

    COPY_EXISTING ~BDSW1H01.ITM~ ~override~
      WRITE_LONG 0x60 3
      LPF ALTER_ITEM_HEADER INT_VAR header_type=1 thac0_bonus = 3 damage_bonus = 3 END

      PATCH_FOR_EACH offset IN 0xc 0x54 BEGIN
        READ_LONG ~%offset%~ desc_strref
            PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
              READ_STRREF ~%offset%~ desc
              INNER_PATCH_SAVE desc ~%desc%~ BEGIN
                REPLACE_TEXTUALLY ~%oldkata4%~ ~%newkata4%~
              END
              SAY_EVALUATED ~%offset%~ ~%desc%~
            END
      END
END

///////////////////////////////////////////////////////////////////////////
// Hindo's Doom +3                                                       //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~SW1H70.ITM~ BEGIN
COPY ~forgotten-armament/eff/update_item/MO1H70.EFF~ ~override~
OUTER_SPRINT oldkata1 @30600
OUTER_SPRINT newkata1 @30601
    
    COPY_EXISTING ~SW1H70.ITM~ ~override~
        LPF ADD_ITEM_EFFECT INT_VAR opcode = 177 type = 1 target = 2 parameter1 = 4 parameter2 = 3 timing = 1 resist_dispel = 0 probability1 = 100 STR_VAR resource = ~mo1h70~ END

        READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldkata1%~ ~%newkata1%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
END

///////////////////////////////////////////////////////////////////////////
// Hindo's Doom +4                                                       //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~SW1H71.ITM~ BEGIN
COPY ~forgotten-armament/eff/update_item/MO1H71.EFF~ ~override~
OUTER_SPRINT oldkata2 @30602
OUTER_SPRINT newkata2 @30603
OUTER_SPRINT oldkata3 @30604
OUTER_SPRINT newkata3 @30605
    
    COPY_EXISTING ~SW1H71.ITM~ ~override~
        LPF ADD_ITEM_EFFECT INT_VAR opcode = 177 type = 1 target = 2 parameter1 = 4 parameter2 = 3 timing = 1 resist_dispel = 0 probability1 = 100 STR_VAR resource = ~mesdie~ END
        LPF ADD_ITEM_EFFECT INT_VAR opcode = 177 type = 1 target = 2 parameter1 = 4 parameter2 = 3 timing = 1 resist_dispel = 0 probability1 = 100 STR_VAR resource = ~die~ END
        LPF ADD_ITEM_EFFECT INT_VAR opcode = 177 type = 1 target = 2 parameter1 = 4 parameter2 = 3 timing = 1 resist_dispel = 0 probability1 = 100 STR_VAR resource = ~mo1h71~ END

        READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldkata2%~ ~%newkata2%~
              REPLACE_TEXTUALLY ~%oldkata3%~ ~%newkata3%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
END

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Long Sword                                                            //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Blackrazor                                                            //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~MISCBC.ITM~ BEGIN
OUTER_SPRINT oldlong1 @30700
OUTER_SPRINT newlong1 @30701

    COPY_EXISTING ~MISCBC.ITM~ ~override~
      WRITE_LONG 0x60 4
      LPF ALTER_ITEM_HEADER INT_VAR header_type=1 thac0_bonus = 4 damage_bonus = 4 END

      PATCH_FOR_EACH offset IN 0x8 0xc 0x54 BEGIN
        READ_LONG ~%offset%~ desc_strref
            PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
              READ_STRREF ~%offset%~ desc
              INNER_PATCH_SAVE desc ~%desc%~ BEGIN
                REPLACE_TEXTUALLY ~%oldlong1%~ ~%newlong1%~
              END
              SAY_EVALUATED ~%offset%~ ~%desc%~
            END
      END
END

///////////////////////////////////////////////////////////////////////////
// Daystar                                                               //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~SW1H31.ITM~ BEGIN
OUTER_SPRINT oldlong2 @30702
OUTER_SPRINT newlong2 @30703

    COPY_EXISTING ~SW1H31.ITM~ ~override~
      WRITE_LONG 0x60 3
      LPF ALTER_ITEM_HEADER INT_VAR header_type=1 thac0_bonus = 3 damage_bonus = 3 END

      PATCH_FOR_EACH offset IN 0xc 0x54 BEGIN
        READ_LONG ~%offset%~ desc_strref
            PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
              READ_STRREF ~%offset%~ desc
              INNER_PATCH_SAVE desc ~%desc%~ BEGIN
                REPLACE_TEXTUALLY ~%oldlong2%~ ~%newlong2%~
              END
              SAY_EVALUATED ~%offset%~ ~%desc%~
            END
      END
END

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Mace                                                                  //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Ardulia's Fall                                                        //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~BLUN20.ITM~ BEGIN
OUTER_SPRINT oldmace1 @30800
OUTER_SPRINT newmace1 @30801
OUTER_SPRINT oldmace2 @30802
OUTER_SPRINT newmace2 @30803
OUTER_SPRINT oldmace3 @30804
OUTER_SPRINT newmace3 @30805
OUTER_SPRINT oldmace5 @30808
OUTER_SPRINT newmace5 @30809

    COPY_EXISTING ~BLUN20.ITM~ ~override~
      WRITE_LONG 0x60 3
      LPF ALTER_ITEM_HEADER INT_VAR header_type=1 thac0_bonus = 3 damage_bonus = 3 END
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 49 target = 1 parameter1 = 2 parameter2 = 0 timing = 2 resist_dispel = 2 probability1 = 100 END
      LPF ALTER_ITEM_EFFECT INT_VAR match_opcode = 0 check_headers = 1 savebonus = ~-2~ END
      LPF ALTER_ITEM_EFFECT INT_VAR match_opcode = 54 check_headers = 1 savebonus = ~-2~ END
      LPF ALTER_ITEM_EFFECT INT_VAR match_opcode = 142 check_headers = 1 savebonus = ~-2~ END
      LPF ALTER_ITEM_EFFECT INT_VAR match_opcode = 139 check_headers = 1 savebonus = ~-2~ END
      LPF ALTER_ITEM_EFFECT INT_VAR match_opcode = 141 check_headers = 1 savebonus = ~-2~ END
      LPF ALTER_ITEM_EFFECT INT_VAR match_opcode = 174 check_headers = 1 savebonus = ~-2~ END
      LPF ALTER_ITEM_EFFECT INT_VAR match_opcode = 40 check_headers = 1 savebonus = ~-2~ END

      PATCH_FOR_EACH offset IN 0xc 0x54 BEGIN
        READ_LONG ~%offset%~ desc_strref
            PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
              READ_STRREF ~%offset%~ desc
              INNER_PATCH_SAVE desc ~%desc%~ BEGIN
                REPLACE_TEXTUALLY ~%oldmace5%~ ~%newmace5%~
                REPLACE_TEXTUALLY ~%oldmace1%~ ~%newmace1%~
                REPLACE_TEXTUALLY ~%oldmace2%~ ~%newmace2%~
                REPLACE_TEXTUALLY ~%oldmace3%~ ~%newmace3%~
              END
              SAY_EVALUATED ~%offset%~ ~%desc%~
            END
      END
END

///////////////////////////////////////////////////////////////////////////
// Krotan's Skullcrusher                                                 //
// +5% crit strike for this weapon                                       //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~BLUN11.ITM~ BEGIN
OUTER_SPRINT oldmace4 @30806
OUTER_SPRINT newmace4 @30807

    COPY_EXISTING ~BLUN11.ITM~ ~override~
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 301 target = 1 parameter1 = 1 parameter2 = 1 timing = 2 resist_dispel = 0 probability1 = 100 END

      READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldmace4%~ ~%newmace4%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
END

///////////////////////////////////////////////////////////////////////////
// Storm Star +5                                                         //
// +2d6 electrical damage                                                //
// 10% chance of chain lightning                                         //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~BLUN29.ITM~ BEGIN
OUTER_SPRINT oldmace6 @30810
OUTER_SPRINT newmace6 @30811
OUTER_SPRINT oldmace7 @30812
OUTER_SPRINT newmace7 @30813

    COPY_EXISTING ~BLUN29.ITM~ ~override~
      LPF ALTER_ITEM_EFFECT INT_VAR match_opcode = 146 check_headers = 1 probability1 = 10 END
      LPF ALTER_ITEM_EFFECT INT_VAR match_opcode = 12 check_headers = 1 dicenumber = 2 END

      READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldmace6%~ ~%newmace6%~
              REPLACE_TEXTUALLY ~%oldmace7%~ ~%newmace7%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
END

///////////////////////////////////////////////////////////////////////////
// Skullcrusher                                                          //
// +10% crit strike with this weapon                                     //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~BLUN18.ITM~ BEGIN
OUTER_SPRINT oldmace8 @30814
OUTER_SPRINT newmace8 @30815
    
    COPY_EXISTING ~BLUN18.ITM~ ~override~
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 301 target = 1 parameter1 = 2 parameter2 = 1 timing = 2 resist_dispel = 0 probability1 = 100 END

      READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldmace8%~ ~%newmace8%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
END

///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////
// Wakizashi                                                             //
///////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
// Yamato +4                                                             //
// +1 APR                                                                //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~SW1H66.ITM~ BEGIN
OUTER_SPRINT oldyamato @31600
OUTER_SPRINT newyamato @31601

    COPY_EXISTING ~SW1H66.ITM~ ~override~ 
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 1 target = 1 parameter1 = 1 parameter2 = 0 timing = 2 resist_dispel = 0 probability1 = 100 END

      READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldyamato%~ ~%newyamato%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
END

///////////////////////////////////////////////////////////////////////////
// Kachiko's Wakizashi +3                                                //
// Increase duration of drain from round to turns                        //
///////////////////////////////////////////////////////////////////////////
ACTION_IF FILE_EXISTS_IN_GAME ~WAWAK.ITM~ BEGIN
OUTER_SPRINT oldwaki1 @31602
OUTER_SPRINT newwaki1 @31603

    COPY_EXISTING ~WAWAK.ITM~ ~override~ 
      LPF ALTER_ITEM_EFFECT INT_VAR match_opcode = 49 check_headers = 1 duration = 120 END

      READ_LONG 0x54 desc_strref
          PATCH_IF (desc_strref >= 0 && desc_strref < 2147483646) BEGIN
            READ_STRREF 0x54 desc
            INNER_PATCH_SAVE desc ~%desc%~ BEGIN
              REPLACE_TEXTUALLY ~%oldwaki1%~ ~%newwaki1%~
            END
            SAY_EVALUATED 0x54 ~%desc%~
          END
END

// Dorn 2h make vorpal
// Silver Sword look at legacy stuff
// Carsomy +20% magic resist