IF
  Global("MO#TOBItemUp","GLOBAL",1)
  Global("ImpForgeStuff","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("ImpForgeStuff","GLOBAL",0)
    GiveItemCreate("moblk01",Player1,0,0,0)
    StartDialogueNoSet(Player1)
END

IF
  Global("MO#TOBItemUp","GLOBAL",2)
  Global("ImpForgeStuff","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("ImpForgeStuff","GLOBAL",0)
    GiveItemCreate("mo2h15",Player1,0,0,0)
    StartDialogueNoSet(Player1)
END